import class inkSliderController extends inkLogicController
{
	public import function Setup( minimumValue : Float, maximumValue : Float, defaultValue : Float, optional step : Float );
	public import function GetProgress() : Float;
	public import function GetCurrentValue() : Float;
	public import function GetMaxValue() : Float;
	public import function GetMinValue() : Float;
	public import function GetStep() : Float;
	public import function GetPercentageHandleSize() : Float;
	public import function SetPercentageHandleSize( newSize : Float );
	public import function SetInputDisabled( disabled : Bool );
	public import function ChangeValue( newValue : Float );
	public import function ChangeProgress( newValue : Float );
	public import function Next();
	public import function Prior();
	public import function GetSlidingAreaRef() : inkWidgetRef;
	public import function GetHandleRef() : inkWidgetRef;
}

import enum inkESliderDirection
{
	Horizontal,
	Vertical,
}

