importonly class inkToggleController extends inkButtonController
{
	public import function Toggle();
	public import function IsToggled() : Bool;
	public import function SetToggled( toggled : Bool );
	public import function GetToggleState() : inkEToggleState;
	public import function IsAutoToggle() : Bool;
	public import function SetAutoToggle( auto : Bool );
}

import enum inkEToggleState
{
	Normal,
	Press,
	Hover,
	Disabled,
	Toggled,
	ToggledPress,
	ToggledHover,
}

