class ServerNodeHealthChangeListener extends CustomValueStatPoolsListener
{
	private var m_serverNode : weak< ServerNode >;

	public static function Create( serverNode : ServerNode ) : ServerNodeHealthChangeListener
	{
		var instance : ServerNodeHealthChangeListener;
		instance = new ServerNodeHealthChangeListener;
		instance.m_serverNode = serverNode;
		return instance;
	}

	public export override function OnStatPoolValueChanged( oldValue : Float, newValue : Float, percToPoints : Float )
	{
		m_serverNode.OnHealthChanged( newValue );
	}

}

