class DebugTextDrawer extends GameObject
{
	private instanceeditable var m_text : String;
	private instanceeditable var m_color : Color;

	protected event OnRequestComponents( ri : EntityRequestComponentsInterface ) {}

	protected event OnTakeControl( ri : EntityResolveComponentsInterface )
	{
		var debugVisualizer : DebugVisualizerSystem;
		debugVisualizer = GameInstance.GetDebugVisualizerSystem( GetGame() );
		debugVisualizer.DrawText3D( GetWorldPosition(), m_text, m_color );
	}

}

