class DEBUG_VirtualShopkeeper extends GameObject
{
	protected instanceeditable var m_vendorID : String;
	default m_vendorID = "Vendors.CCLVendor";

	protected event OnInteractionChoice( choiceEvent : InteractionChoiceEvent )
	{
		var blackboard : IBlackboard;
		var data : VendorData;
		blackboard = GameInstance.GetBlackboardSystem( GetGame() ).Get( GetAllBlackboardDefs().UI_Vendor );
		data.vendorId = m_vendorID;
		data.entityID = this.GetEntityID();
		data.isActive = true;
		blackboard.SetVariant( GetAllBlackboardDefs().UI_Vendor.VendorData, data );
		blackboard.SignalVariant( GetAllBlackboardDefs().UI_Vendor.VendorData );
	}

}

