class BinkVideoEvent extends Event
{
	var path : ResRef;
	var startingTime : Float;
	var shouldPlay : Bool;
}

importonly struct BinkVideoSummary
{
	import var currentTimeMs : Uint32;
	import var totalTimeMs : Uint32;
	import var currentFrame : Uint32;
	import var totalFrames : Uint32;
	import var frameRate : Uint32;
}

importonly class BinkComponent extends IVisualComponent
{
	public import function SetVideoPlayerName( videoPlayerName : CName );
	public import function SetVideoPath( videoPath : ResRef );
	public import function SetIsLooped( loopVideo : Bool );
	public import function ForceVideoFrameRate( forceVideoFrameRate : Bool );
	public import function Play();
	public import function Stop();
	public import function Pause( pauseVideo : Bool );
	public import function IsPaused();
	public import function SkipFrames( numberOfFrames : Int32 );
	public import function SkipFramePercentage( percentage : Int32 );
	public import function GetVideoSummary() : BinkVideoSummary;
}

