class FeedEvent extends Event
{
	var On : Bool;
	var virtualComponentName : CName;
	var cameraID : EntityID;
}

class VRoomFeed extends Event
{
	var On : Bool;
}

importonly final class VirtualCameraComponent extends entCameraComponent
{
	public import function GetVirtualCameraName() : CName;
	public import function SetVirtualCameraName( newName : CName );
}

importonly class VirtualCameraViewComponent extends IVisualComponent
{
	public import function GetVirtualCameraName() : CName;
	public import function SetVirtualCameraName( newName : CName );
}

class ScriptableVirtualCameraViewComponent extends VirtualCameraViewComponent
{

	protected event OnFeedChange( evt : FeedEvent )
	{
		Toggle( evt.On );
	}

}

