class StatsManager
{
	var m_playerGodModeModifierData : gameStatModifierData;

	public static function GetObjectDPS( obj : GameObject ) : DPSPackage
	{
		var i : Int32;
		var dmgVal : Float;
		var statsSystem : StatsSystem;
		var newPackage : DPSPackage;
		var objectID : StatsObjectID;
		objectID = obj.GetEntityID();
		statsSystem = GameInstance.GetStatsSystem( obj.GetGame() );
		for( i = 0; i < ( ( Int32 )( gamedataDamageType.Count ) ); i += 1 )
		{
			dmgVal = statsSystem.GetStatValue( objectID, statsSystem.GetStatType( ( ( gamedataDamageType )( i ) ) ) );
			if( dmgVal > 0.0 )
			{
				newPackage.value = dmgVal;
				newPackage.type = ( ( gamedataDamageType )( i ) );
				return newPackage;
			}
		}
		return newPackage;
	}

}

struct DPSPackage
{
	var value : Float;
	var type : gamedataDamageType;
}

