class SimpleOnTurnOnPlayEffectDeviceController extends ScriptableDeviceComponent
{

	public const override function GetPS() : SimpleOnTurnOnPlayEffectDeviceControllerPS
	{
		return ( ( SimpleOnTurnOnPlayEffectDeviceControllerPS )( GetBasePS() ) );
	}

}

class SimpleOnTurnOnPlayEffectDeviceControllerPS extends ScriptableDeviceComponentPS
{

	protected override function GameAttached() {}

	protected override function LogicReady()
	{
		super.LogicReady();
		m_isAttachedToGame = true;
	}

}

