class StrikeExecutor_Debug_ModifyStatPool extends StrikeExecutor_Debug
{

	public function Process( ctx : EffectScriptContext, applierCtx : EffectExecutionScriptContext ) : Bool
	{
		var puppet : ScriptedPuppet;
		var data : EffectData;
		var statPool : Int32;
		var statPoolType : gamedataStatPoolType;
		var value : Float;
		var isPercent : Bool;
		var puppetID : StatsObjectID;
		puppet = ( ( ScriptedPuppet )( EffectExecutionScriptContext.GetTarget( applierCtx ) ) );
		puppetID = puppet.GetEntityID();
		if( puppet )
		{
			data = EffectScriptContext.GetSharedData( ctx );
			EffectData.GetInt( data, GetAllBlackboardDefs().EffectSharedData.statType, statPool );
			EffectData.GetFloat( data, GetAllBlackboardDefs().EffectSharedData.value, value );
			EffectData.GetBool( data, GetAllBlackboardDefs().EffectSharedData.debugBool, isPercent );
			statPoolType = ( ( gamedataStatPoolType )( statPool ) );
			GameInstance.GetStatPoolsSystem( puppet.GetGame() ).RequestSettingStatPoolValue( puppetID, statPoolType, value, NULL, isPercent );
			return true;
		}
		else
		{
			LogStrike( "StrikeExecutor_ModifyStat.Process(): provided object is not a puppet!" );
		}
		return false;
	}

}

