class StrikeExecutor_Debug_PrintStat extends StrikeExecutor_Debug
{

	public function Process( ctx : EffectScriptContext, applierCtx : EffectExecutionScriptContext ) : Bool
	{
		var puppet : ScriptedPuppet;
		var data : EffectData;
		var stat : Int32;
		var statType : gamedataStatType;
		var statTypeString : String;
		var value : Float;
		var puppetID : StatsObjectID;
		puppet = ( ( ScriptedPuppet )( EffectExecutionScriptContext.GetTarget( applierCtx ) ) );
		puppetID = puppet.GetEntityID();
		if( puppet )
		{
			data = EffectScriptContext.GetSharedData( ctx );
			EffectData.GetInt( data, GetAllBlackboardDefs().EffectSharedData.statType, stat );
			statType = ( ( gamedataStatType )( stat ) );
			value = GameInstance.GetStatsSystem( puppet.GetGame() ).GetStatValue( puppetID, statType );
			statTypeString = EnumValueToString( "gamedataStatType", stat );
			LogStats( "" );
			LogStats( ( "---- stat of " + puppet ) + " ----" );
			LogStats( ( ( "Stat: " + statTypeString ) + " Value: " ) + value );
			LogStats( "" );
			return true;
		}
		else
		{
			LogStrike( "StrikeExecutor_PrintStat.Process(): provided object is not a puppet!" );
		}
		return false;
	}

}

