class HighlightObjectEffector extends Effector
{
	var m_reason : CName;

	protected override function Initialize( record : TweakDBID, game : GameInstance, parentRecord : TweakDBID )
	{
		m_reason = 'HighlightObjectEffector' + StringToName( IntToString( RandRange( 0, 5000 ) ) );
	}

	protected override function ActionOn( owner : GameObject )
	{
		GameObject.SendForceRevealObjectEvent( owner, true, m_reason );
	}

	protected override function ActionOff( owner : GameObject )
	{
		GameObject.SendForceRevealObjectEvent( owner, false, m_reason );
	}

}

