class RemoveAllStatusEffectsEffector extends Effector
{

	protected override function ActionOn( owner : GameObject )
	{
		var effects : array< StatusEffect >;
		var i : Int32;
		var seSys : StatusEffectSystem;
		seSys = GameInstance.GetStatusEffectSystem( owner.GetGame() );
		seSys.GetAppliedEffects( owner.GetEntityID(), effects );
		for( i = 0; i < effects.Size(); i += 1 )
		{
			seSys.RemoveStatusEffect( owner.GetEntityID(), effects[ i ].GetRecord().GetID() );
		}
	}

}

