class SetTargetHealthEffector extends Effector
{
	var m_healthValueToSet : Float;

	protected override function Initialize( record : TweakDBID, game : GameInstance, parentRecord : TweakDBID )
	{
		m_healthValueToSet = TweakDBInterface.GetFloat( record + T".healthValueToSet", 0.0 );
	}

	protected override function ActionOn( owner : GameObject )
	{
		var target : NPCPuppet;
		target = ( ( NPCPuppet )( owner ) );
		Set( target );
	}

	private function Set( target : NPCPuppet )
	{
		if( !( target ) )
		{
			return;
		}
		GameInstance.GetStatPoolsSystem( target.GetGame() ).RequestChangingStatPoolValue( target.GetEntityID(), gamedataStatPoolType.Health, m_healthValueToSet, NULL, true, true );
	}

}

