import enum EVisualizerActivityState
{
	Visible,
	Available,
	Active,
}

importonly struct ListChoiceData
{
	import var localizedName : String;
	import var type : ChoiceTypeWrapper;
	import var inputActionName : CName;
	import var captionParts : InteractionChoiceCaption;
	import var timeProvider : weak< IVisualizerTimeProvider >;
}

importonly struct ListChoiceHubData
{
	import var id : Int32;
	import var activityState : EVisualizerActivityState;
	import var flags : EVisualizerDefinitionFlags;
	import var isPhoneLockActive : Bool;
	import var title : String;
	import var choices : array< ListChoiceData >;
	import var timeProvider : weak< IVisualizerTimeProvider >;
}

importonly struct DialogChoiceHubs
{
	import var choiceHubs : array< ListChoiceHubData >;
}

