class InventoryCyberwareDisplayController extends InventoryItemDisplayController
{
	protected editable var m_ownedFrame : inkWidgetRef;
	protected editable var m_selectedFrame : inkWidgetRef;
	protected editable var m_amountPanel : inkWidgetRef;
	protected editable var m_amount : inkTextRef;

	public override function Unselect()
	{
		inkWidgetRef.SetVisible( m_selectedFrame, false );
	}

	public override function Select()
	{
		inkWidgetRef.SetVisible( m_selectedFrame, true );
	}

	public function SetAmountOfNewItem( amount : Int32 )
	{
		if( amount <= 0 )
		{
			inkWidgetRef.SetVisible( m_amountPanel, false );
		}
		else
		{
			inkWidgetRef.SetVisible( m_amountPanel, true );
			inkTextRef.SetText( m_amount, IntToString( amount ) );
		}
	}

}

