class PaperdollGlitchController extends inkLogicController
{
	protected editable var m_PaperdollGlichRoot : inkWidgetRef;
	private editable var m_GlitchAnimationName : CName;

	protected event OnInitialize()
	{
		inkWidgetRef.Get( m_PaperdollGlichRoot ).SetEffectEnabled( inkEffectType.Glitch, 'Glitch_0', true );
		inkWidgetRef.Get( m_PaperdollGlichRoot ).SetEffectEnabled( inkEffectType.BoxBlur, 'BoxBlur_0', true );
		PlayLibraryAnimation( m_GlitchAnimationName );
		if( IsNameValid( m_GlitchAnimationName ) )
		{
			PlayLibraryAnimation( m_GlitchAnimationName );
		}
	}

}

