enum ERadioStationList
{
	AGGRO_INDUSTRIAL = 0,
	ELECTRO_INDUSTRIAL = 1,
	HIP_HOP = 2,
	AGGRO_TECHNO = 3,
	DOWNTEMPO = 4,
	ATTITUDE_ROCK = 5,
	POP = 6,
	LATINO = 7,
	METAL = 8,
	MINIMAL_TECHNO = 9,
	JAZZ = 10,
	GROWL = 11,
	DARK_STAR = 12,
	IMPULSE_FM = 13,
}

class RadioStationDataProvider
{

	public constexpr static function GetStationsCount() : Int32
	{
		return 14;
	}

	public static function GetStationName( radioStationType : ERadioStationList ) : CName
	{
		switch( radioStationType )
		{
			case ERadioStationList.AGGRO_INDUSTRIAL:
				return 'radio_station_02_aggro_ind';
			case ERadioStationList.ELECTRO_INDUSTRIAL:
				return 'radio_station_03_elec_ind';
			case ERadioStationList.HIP_HOP:
				return 'radio_station_04_hiphop';
			case ERadioStationList.AGGRO_TECHNO:
				return 'radio_station_07_aggro_techno';
			case ERadioStationList.DOWNTEMPO:
				return 'radio_station_09_downtempo';
			case ERadioStationList.ATTITUDE_ROCK:
				return 'radio_station_01_att_rock';
			case ERadioStationList.POP:
				return 'radio_station_05_pop';
			case ERadioStationList.LATINO:
				return 'radio_station_10_latino';
			case ERadioStationList.METAL:
				return 'radio_station_11_metal';
			case ERadioStationList.MINIMAL_TECHNO:
				return 'radio_station_06_minim_techno';
			case ERadioStationList.JAZZ:
				return 'radio_station_08_jazz';
			case ERadioStationList.GROWL:
				return 'radio_station_12_growl_fm';
			case ERadioStationList.DARK_STAR:
				return 'radio_station_13_dark_star';
			case ERadioStationList.IMPULSE_FM:
				return 'radio_station_14_impulse_fm';
		}
		return 'station_none';
	}

	public static function GetStationNameByIndex( index : Int32 ) : CName
	{
		return GetStationName( ( ( ERadioStationList )( index ) ) );
	}

	public static function GetChannelName( radioStationType : ERadioStationList ) : String
	{
		switch( radioStationType )
		{
			case ERadioStationList.AGGRO_INDUSTRIAL:
				return "Gameplay-Devices-Radio-RadioStationAggroIndie";
			case ERadioStationList.ELECTRO_INDUSTRIAL:
				return "Gameplay-Devices-Radio-RadioStationElectroIndie";
			case ERadioStationList.HIP_HOP:
				return "Gameplay-Devices-Radio-RadioStationHipHop";
			case ERadioStationList.AGGRO_TECHNO:
				return "Gameplay-Devices-Radio-RadioStationAggroTechno";
			case ERadioStationList.DOWNTEMPO:
				return "Gameplay-Devices-Radio-RadioStationDownTempo";
			case ERadioStationList.ATTITUDE_ROCK:
				return "Gameplay-Devices-Radio-RadioStationAttRock";
			case ERadioStationList.POP:
				return "Gameplay-Devices-Radio-RadioStationPop";
			case ERadioStationList.LATINO:
				return "Gameplay-Devices-Radio-RadioStationLatino";
			case ERadioStationList.METAL:
				return "Gameplay-Devices-Radio-RadioStationMetal";
			case ERadioStationList.MINIMAL_TECHNO:
				return "Gameplay-Devices-Radio-RadioStationMinimalTechno";
			case ERadioStationList.JAZZ:
				return "Gameplay-Devices-Radio-RadioStationJazz";
			case ERadioStationList.GROWL:
				return "Gameplay-Devices-Radio-RadioStationGrowlFm";
			case ERadioStationList.DARK_STAR:
				return "Gameplay-Devices-Radio-RadioStationDarkStar";
			case ERadioStationList.IMPULSE_FM:
				return "Gameplay-Devices-Radio-RadioStationImpulseFM";
		}
		return "";
	}

	public static function GetRandomStation() : ERadioStationList
	{
		return ( ( ERadioStationList )( RandRange( 0, RadioStationDataProvider.GetStationsCount() ) ) );
	}

	public static function GetNextStationTo( station : ERadioStationList ) : ERadioStationList
	{
		var currentStationIndex : Int32;
		var nextStationIndex : Int32;
		currentStationIndex = GetStationIndex( station );
		nextStationIndex = ( currentStationIndex + 1 ) % GetStationsCount();
		return ( ( ERadioStationList )( nextStationIndex ) );
	}

	public static function GetPreviousStationTo( station : ERadioStationList ) : ERadioStationList
	{
		var currentStationIndex : Int32;
		var previousStationIndex : Int32;
		currentStationIndex = GetStationIndex( station );
		previousStationIndex = ( ( currentStationIndex - 1 ) + GetStationsCount() ) % GetStationsCount();
		return ( ( ERadioStationList )( previousStationIndex ) );
	}

	private static function GetStationIndex( station : ERadioStationList ) : Int32
	{
		return Clamp( ( ( Int32 )( station ) ), 0, GetStationsCount() - 1 );
	}

}

