importonly class MappinScriptData extends IScriptable
{
	import var statPoolType : gamedataStatPoolType;
}

class TestMappinScriptData extends MappinScriptData
{
	var test : Int32;
}

importonly struct IMappinData
{
}

importonly struct MappinData extends IMappinData
{
	import var mappinType : TweakDBID;
	import var variant : gamedataMappinVariant;
	import var active : Bool;
	import var debugCaption : String;
	import var visibleThroughWalls : Bool;
	import var scriptData : MappinScriptData;
}

importonly struct NewMappinID
{
	import var value : Uint64;
}

exec function pindatatest( instance : GameInstance )
{
	var mappinData : MappinData;
	var scriptData : TestMappinScriptData;
	var otherScriptData : TestMappinScriptData;
	scriptData = new TestMappinScriptData;
	scriptData.test = 5;
	mappinData.scriptData = scriptData;
	otherScriptData = ( ( TestMappinScriptData )( mappinData.scriptData ) );
	Log( "test " + otherScriptData.test );
}

