class SlotAnimationInProgress extends AIbehaviorconditionScript
{

	protected export override function Activate( context : ScriptExecutionContext )
	{
		SetUpdateInterval( context, RandomizeOffsetForUpdateInterval( 0.1 ) );
	}

	protected export override function Check( context : ScriptExecutionContext ) : AIbehaviorConditionOutcomes
	{
		return GetPuppet( context ).GetPuppetStateBlackboard().GetBool( GetAllBlackboardDefs().PuppetState.SlotAnimationInProgress );
	}

}

