class hudJohnnyController extends inkHUDGameController
{
	private editable var m_tourHeader : inkTextRef;
	private editable var m_leftDates : inkTextRef;
	private editable var m_rightDates : inkTextRef;
	private editable var m_cancelled : inkWidgetRef;
	private var m_gameInstance : GameInstance;

	protected event OnPlayerAttach( playerPuppet : GameObject )
	{
		m_gameInstance = GetPlayerControlledObject().GetGame();
		GetRootWidget().SetVisible( false );
		if( GameInstance.GetQuestsSystem( m_gameInstance ).GetFact( 'q108_active' ) == 1 )
		{
			inkTextRef.SetText( m_tourHeader, "LocKey#54096" );
			inkTextRef.SetText( m_leftDates, "LocKey#54092" );
			inkTextRef.SetText( m_rightDates, "LocKey#54094" );
			inkWidgetRef.SetVisible( m_cancelled, false );
			GetRootWidget().SetVisible( true );
		}
		else if( GameInstance.GetQuestsSystem( m_gameInstance ).GetFact( 'q101_active' ) == 1 )
		{
			inkTextRef.SetText( m_tourHeader, "LocKey#54097" );
			inkTextRef.SetText( m_leftDates, "LocKey#54100" );
			inkTextRef.SetText( m_rightDates, "LocKey#54101" );
			inkWidgetRef.SetVisible( m_cancelled, false );
			GetRootWidget().SetVisible( true );
		}
		else if( GameInstance.GetQuestsSystem( m_gameInstance ).GetFact( 'q101_johnny_tour_cancelled' ) == 1 )
		{
			inkTextRef.SetText( m_tourHeader, "LocKey#54102" );
			inkTextRef.SetText( m_leftDates, "LocKey#54100" );
			inkTextRef.SetText( m_rightDates, "LocKey#54101" );
			inkWidgetRef.SetVisible( m_cancelled, true );
			GetRootWidget().SetVisible( true );
		}
	}

}

