class ActionsSequencer extends InteractiveMasterDevice
{
	default m_controllerTypeName = 'ActionsSequencerController';

	protected event OnTakeControl( ri : EntityResolveComponentsInterface )
	{
		super.OnTakeControl( ri );
		m_controller = ( ( ActionsSequencerController )( EntityResolveComponentsInterface.GetComponent( ri, 'controller' ) ) );
	}

	private const override function GetController() : ActionsSequencerController
	{
		return ( ( ActionsSequencerController )( m_controller ) );
	}

	public const override function GetDevicePS() : ActionsSequencerControllerPS
	{
		return GetController().GetPS();
	}

}

