class Fuse extends InteractiveMasterDevice
{
	default m_controllerTypeName = 'FuseController';

	protected event OnRequestComponents( ri : EntityRequestComponentsInterface )
	{
		EntityRequestComponentsInterface.RequestComponent( ri, 'DeviceTimetable', 'DeviceTimetable', true );
		super.OnRequestComponents( ri );
	}

	protected event OnTakeControl( ri : EntityResolveComponentsInterface )
	{
		m_controller = ( ( FuseController )( EntityResolveComponentsInterface.GetComponent( ri, 'controller' ) ) );
	}

	protected const override function GetController() : FuseController
	{
		return ( ( FuseController )( m_controller ) );
	}

	public const override function GetDevicePS() : FuseControllerPS
	{
		return GetController().GetPS();
	}

	public const override function GetDefaultHighlight() : FocusForcedHighlightData
	{
		return NULL;
	}

	public const override function IsGameplayRelevant() : Bool
	{
		return false;
	}

	public const override function ShouldSendGameAttachedEventToPS() : Bool
	{
		return false;
	}

}

