class KurtzComponent extends ScriptableComponent
{

	private function OnGameAttach() {}

	protected event OnAIEvent( aiEvent : AIEvent )
	{
		switch( aiEvent.name )
		{
			case 'ScannerOn':
				GameObject.StartReplicatedEffectEvent( GetOwner(), 'scanner' );
			break;
			case 'ScannerOff':
				GameObject.BreakReplicatedEffectLoopEvent( GetOwner(), 'scanner' );
			break;
		}
	}

	private export function OnGameDetach()
	{
		GameObject.BreakReplicatedEffectLoopEvent( GetOwner(), 'scanner' );
	}

	protected event OnDefeated( evt : DefeatedEvent )
	{
		GameObject.BreakReplicatedEffectLoopEvent( GetOwner(), 'scanner' );
	}

	protected event OnDeath( evt : gameDeathEvent )
	{
		GameObject.BreakReplicatedEffectLoopEvent( GetOwner(), 'scanner' );
	}

}

