class LevelUpUserData extends inkGameNotificationData
{
	var data : LevelUpData;
}

class NewAreaDiscoveredUserData extends inkGameNotificationData
{
	var data : String;
}

class ItemLogUserData extends inkGameNotificationData
{
	var itemID : ItemID;
	var itemLogQueueEmpty : Bool;
	default itemLogQueueEmpty = false;
}

class JournalNotificationData extends inkGameNotificationData
{
	var journalEntry : weak< JournalEntry >;
	var journalEntryState : gameJournalEntryState;
	var className : CName;
	var menuMode : Bool;
}

class QuestUpdateUserData extends inkGameNotificationData
{
	var data : weak< JournalQuest >;
}

class NewCodexEntryUserData extends inkGameNotificationData
{
	var data : String;
}

class CustomQuestNotificationUserData extends inkGameNotificationData
{
	var data : CustomQuestNotificationData;
}

