class PatchNotePopupController extends inkGameController
{

	protected event OnInitialize()
	{
		RegisterToGlobalInputCallback( 'OnPostOnPress', this, 'OnHandlePressInput' );
	}

	protected event OnUninitialize()
	{
		UnregisterFromGlobalInputCallback( 'OnPostOnPress', this, 'OnHandlePressInput' );
	}

	protected event OnHandlePressInput( evt : inkPointerEvent )
	{
		if( evt.IsAction( 'cancel' ) )
		{
		}
	}

}

