class RemotePlayerMappinController extends BaseInteractionMappinController
{
	private var m_mappin : weak< RemotePlayerMappin >;
	private var m_root : weak< inkWidget >;

	protected event OnInitialize() {}

	protected event OnUninitialize() {}

	protected event OnIntro()
	{
		m_mappin = ( ( RemotePlayerMappin )( GetMappin() ) );
		m_root = GetRootWidget();
		OnUpdate();
	}

	protected event OnUpdate()
	{
		SetRootVisible( m_mappin.vitals == ( ( Int32 )( gamePSMVitals.Dead ) ) );
	}

}

