class IsPlayerPrereqState extends PrereqState
{
}

class IsPlayerPrereq extends IScriptablePrereq
{
	var m_invert : Bool;

	protected export override function Initialize( recordID : TweakDBID )
	{
		m_invert = TweakDBInterface.GetBool( recordID + T".invert", false );
	}

	protected export const override function OnApplied( state : PrereqState, game : GameInstance, context : IScriptable )
	{
		state.OnChanged( IsFulfilled( game, context ) );
	}

	public const override function IsFulfilled( game : GameInstance, context : IScriptable ) : Bool
	{
		var checkPassed : Bool;
		var owner : weak< ScriptedPuppet >;
		owner = ( ( ScriptedPuppet )( context ) );
		if( owner )
		{
			checkPassed = owner.IsPlayer();
			if( m_invert )
			{
				checkPassed = !( checkPassed );
			}
			return checkPassed;
		}
		return false;
	}

}

