class IsPlayerReachablePrereqState extends PrereqState
{
}

class IsPlayerReachablePrereq extends IScriptablePrereq
{
	var m_invert : Bool;
	var m_checkRMA : Bool;

	protected override function Initialize( recordID : TweakDBID )
	{
		m_invert = TweakDBInterface.GetBool( recordID + T".invert", false );
		m_checkRMA = TweakDBInterface.GetBool( recordID + T".checkForRMA", false );
	}

	public const override function IsFulfilled( game : GameInstance, context : IScriptable ) : Bool
	{
		var checkNavigationPassed : Bool;
		var checkRMAPassed : Bool;
		var owner : weak< ScriptedPuppet >;
		var player : weak< ScriptedPuppet >;
		player = ( ( ScriptedPuppet )( GetPlayer( game ) ) );
		owner = ( ( ScriptedPuppet )( context ) );
		if( owner && player )
		{
			if( m_checkRMA )
			{
				checkRMAPassed = AIActionHelper.IsPointInRestrictedMovementArea( owner, player.GetWorldPosition() );
			}
			if( !( m_invert ) && !( checkRMAPassed ) )
			{
				return false;
			}
			checkNavigationPassed = AINavigationSystem.HasPathFromAtoB( owner, game, owner.GetWorldPosition(), player.GetWorldPosition() );
			if( m_invert )
			{
				return !( checkNavigationPassed ) || !( checkRMAPassed );
			}
			return checkNavigationPassed && checkRMAPassed;
		}
		return false;
	}

}

