importonly struct SDOSink
{
	public import static function SetRoot( sink : SDOSink, rootPath : String );
	public import static function SetKeyColor( sink : SDOSink, key : String, color : Color );
	public import static function PushName( sink : SDOSink, key : String, value : CName );
	public import static function PushString( sink : SDOSink, key : String, value : String );
	public import static function PushVector4( sink : SDOSink, key : String, value : Vector4 );
	public import static function PushVector2( sink : SDOSink, key : String, value : Vector2 );
	public import static function PushQuaternion( sink : SDOSink, key : String, value : Quaternion );
	public import static function PushFloat( sink : SDOSink, key : String, value : Float );
	public import static function PushInt32( sink : SDOSink, key : String, value : Int32 );
	public import static function PushUint32( sink : SDOSink, key : String, value : Uint32 );
	public import static function PushBool( sink : SDOSink, key : String, value : Bool );
	public import static function ClearKey( sink : SDOSink, key : String );
	public import static function RegisterListener_OnClicked( sink : SDOSink, system : weak< ScriptableSystem >, key : String ) : CName;
	public import static function UnregisterListener_OnClicked( sink : SDOSink, system : weak< ScriptableSystem >, fullPath : CName );
}

importonly final class SDOClickedRequest extends ScriptableSystemRequest
{
	import var fullPath : CName;
	import var key : CName;
}

