importonly class inkAnimBuilder extends IScriptable
{
	public import function Interpolate( const interpolatorName : CName, const startValue : Variant, const endValue : Variant ) : inkAnimBuilder;
	public import function InterpolateFrom( const interpolatorName : CName, const startValue : Variant ) : inkAnimBuilder;
	public import function InterpolateTo( const interpolatorName : CName, const endValue : Variant ) : inkAnimBuilder;
	public import function Mode( mode : inkanimInterpolationMode ) : inkAnimBuilder;
	public import function Type( type : inkanimInterpolationType ) : inkAnimBuilder;
	public import function Duration( duration : Float ) : inkAnimBuilder;
	public import function Delay( delay : Float ) : inkAnimBuilder;
	public import function Offset( offset : Float ) : inkAnimBuilder;
	public import function Additive( isAdditive : Bool ) : inkAnimBuilder;
	public import function Relative( useRelativeDuration : Bool ) : inkAnimBuilder;
	public import function Play() : Bool;
	public import function PlayWithOptions( playbackOptions : inkAnimOptions ) : Bool;
}

importonly class inkAnimController extends IScriptable
{
	public import function Select( widget : inkWidget, optional selectionRule : inkSelectionRule, optional param : String ) : inkAnimController;
	public import function FromSet( other : inkWidgetsSet ) : inkAnimController;
	public import function Caller( caller : inkWidget ) : inkAnimController;
	public import function PlayOffset( offset : Float ) : inkAnimController;
	public import function Interpolate( interpolatorName : CName, startValue : Variant, endValue : Variant ) : inkAnimBuilder;
	public import function InterpolateFrom( interpolatorName : CName, startValue : Variant ) : inkAnimBuilder;
	public import function InterpolateTo( interpolatorName : CName, endValue : Variant ) : inkAnimBuilder;
	public import function Play() : Bool;
	public import function PlayWithOptions( playbackOptions : inkAnimOptions ) : Bool;
	public import function GetProxy( const index : Uint32 ) : inkAnimProxy;
	public import function Stop();
	public import function Pause();
	public import function Resume();
	public import function RegisterToCallback( eventType : inkanimEventType, object : IScriptable, functionName : CName );
	public import function UnregisterFromCallback( eventType : inkanimEventType, object : IScriptable, functionName : CName );
}

