importonly class inkEvent extends Event
{
	public import const function IsCanceled() : Bool;
	public import const function Cancel();
	public import const function IsHandled() : Bool;
	public import const function Handle();
	public import const function GetCurrentTarget() : weak< inkWidget >;
	public import const function GetTarget() : weak< inkWidget >;
	public import const function GetDebugString() : String;
}

importonly final class inkLocalizationChangedEvent extends inkEvent
{
}

importonly class inkActionName extends IScriptable
{
	public import const function IsAction( actionName : CName ) : Bool;
}

importonly class inkInputEvent extends inkEvent
{
	public import const function IsAction( actionName : CName ) : Bool;
	public import const function GetActionName() : inkActionName;
	public import const function GetHoldProgress() : Float;
	public import const function IsConsumed() : Bool;
	public import const function Consume();
	public import const function IsShiftDown() : Bool;
	public import const function IsLeftShiftDown() : Bool;
	public import const function IsRightShiftDown() : Bool;
	public import const function IsControlDown() : Bool;
	public import const function IsLeftControlDown() : Bool;
	public import const function IsRightControlDown() : Bool;
	public import const function IsAltDown() : Bool;
	public import const function IsLeftAltDown() : Bool;
	public import const function IsRightAltDown() : Bool;
	public import const function IsCommandDown() : Bool;
	public import const function IsLeftCommandDown() : Bool;
	public import const function IsRightCommandDown() : Bool;
	public import const function IsCapsLocked() : Bool;
}

importonly final class inkPointerEvent extends inkInputEvent
{
	public import const function GetScreenSpacePosition() : Vector2;
	public import const function GetWindowSpacePosition() : Vector2;
	public import const function GetAxisData() : Float;
}

importonly final class inkCharacterEvent extends inkInputEvent
{
	public import const function GetCharacter() : Uint8;
}

