import class inkUserData extends IScriptable
{
}

import class inkCursorInfo extends inkUserData
{
	public import function SetSize( size : Vector2 );
	public import function SetResizableWidget( widget : weak< inkWidget > );
	public import function GetResizableWidgetSize() : Vector2;

	import var pos : Vector2;
	import var isVisible : Bool;
	import var cursorForDevice : CName;
}

import class inkLanguageOverrideProvider extends inkUserData
{
	public import function SetLanguage( lang : scnDialogLineLanguage );
}

class LabeledCursorData extends inkUserData
{
	var m_text : String;
}

import class inkHoldControllerActionData extends inkUserData
{
	public import function SetActionName( actionName : CName );
	public import function GetActionName() : CName;
}

