class PhoneContactItemVirtualController extends inkVirtualCompoundItemController
{
	private editable var m_label : inkTextRef;
	private editable var m_msgCount : inkTextRef;
	private editable var m_msgIndicator : inkWidgetRef;
	private editable var m_questFlag : inkWidgetRef;
	private editable var m_regFlag : inkWidgetRef;
	private var m_animProxyQuest : inkAnimProxy;
	private var m_animProxySelection : inkAnimProxy;
	private var m_contactData : ContactData;

	public function GetContactData() : ContactData
	{
		return m_contactData;
	}

	protected event OnInitialize()
	{
		RegisterToCallback( 'OnSelected', this, 'OnSelected' );
		RegisterToCallback( 'OnDeselected', this, 'OnDeselected' );
	}

	protected event OnDataChanged( value : Variant )
	{
		var playbackOptions : inkAnimOptions;
		m_contactData = ( ( ContactData )( ( ( IScriptable )value ) ) );
		inkTextRef.SetText( m_label, m_contactData.localizedName );
		inkWidgetRef.SetVisible( m_questFlag, m_contactData.questRelated );
		inkWidgetRef.SetVisible( m_regFlag, !( m_contactData.questRelated ) );
		if( m_animProxySelection )
		{
			m_animProxySelection.GotoStartAndStop( true );
			m_animProxySelection = NULL;
		}
		if( m_animProxyQuest )
		{
			m_animProxyQuest.Stop( true );
		}
		if( m_contactData.questRelated )
		{
			playbackOptions.loopType = inkanimLoopType.PingPong;
			playbackOptions.loopInfinite = true;
			m_animProxyQuest = PlayLibraryAnimation( 'questMarker', playbackOptions );
		}
		if( m_contactData.unreadMessages.Size() > 0 )
		{
			inkWidgetRef.SetVisible( m_msgIndicator, true );
			inkTextRef.SetText( m_msgCount, ( ( String )( m_contactData.unreadMessages.Size() ) ) );
		}
		else
		{
			inkWidgetRef.SetVisible( m_msgIndicator, false );
		}
	}

	protected event OnSelected( itemController : weak< inkVirtualCompoundItemController >, discreteNav : Bool )
	{
		if( m_animProxySelection )
		{
			m_animProxySelection.GotoStartAndStop( true );
			m_animProxySelection = NULL;
		}
		m_animProxySelection = PlayLibraryAnimation( 'contactSelected' );
		GetRootWidget().SetState( 'Active' );
	}

	protected event OnDeselected( itemController : weak< inkVirtualCompoundItemController > )
	{
		if( m_animProxySelection )
		{
			m_animProxySelection.GotoStartAndStop( true );
			m_animProxySelection = NULL;
		}
		GetRootWidget().SetState( 'Default' );
	}

}

