class CpoHudRootGameController extends inkGameController
{
	var m_hitIndicator : weak< inkWidget >;
	var m_chatBox : weak< inkWidget >;
	var m_playerList : weak< inkWidget >;
	var m_narration_journal : weak< inkWidget >;
	var m_narrative_plate : weak< inkWidget >;
	var m_inventory : weak< inkWidget >;
	var m_loadouts : weak< inkWidget >;

	protected event OnInitialize()
	{
		m_inventory = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\inventory\inventory.inkwidget", 'Root' ) ) );
		m_inventory.SetAnchor( inkEAnchor.BottomCenter );
		m_inventory.SetAnchorPoint( 0.5, 0.0 );
		m_inventory.SetMargin( 0.0, 0.0, 0.0, 330.0 );
		m_hitIndicator = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\target_hit_indicator\target_hit_indicator.inkwidget", 'Root' ) ) );
		m_hitIndicator.SetAnchor( inkEAnchor.Centered );
		m_hitIndicator.SetAnchorPoint( 0.5, 0.5 );
		m_chatBox = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\chat_box\chat_box.inkwidget", 'Root' ) ) );
		m_chatBox.SetAnchor( inkEAnchor.CenterLeft );
		m_chatBox.SetAnchorPoint( 0.0, 1.0 );
		m_playerList = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\player_list\player_list.inkwidget", 'Root' ) ) );
		m_playerList.SetAnchor( inkEAnchor.CenterRight );
		m_playerList.SetAnchorPoint( 1.0, 0.5 );
		m_narration_journal = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\narration_journal\narration_journal.inkwidget", 'Root' ) ) );
		m_narration_journal.SetAnchor( inkEAnchor.CenterLeft );
		m_narration_journal.SetAnchorPoint( 0.0, -0.1 );
		m_narrative_plate = ( ( inkWidget )( SpawnFromExternal( GetRootWidget(), R"multi\gameplay\gui\widgets\narrative_plate\narrative_plate.inkwidget", 'Root' ) ) );
		m_narrative_plate.SetAnchor( inkEAnchor.TopLeft );
		m_narrative_plate.SetAnchorPoint( 0.0, 0.0 );
	}

	protected event OnUninitialize() {}
}

