class customGameNotificationDataSet extends inkGameNotificationData
{
	var customText : CName;
	var testBool : Bool;
}

class gameNotificationsTest extends inkGameController
{
	var token : inkGameNotificationToken;

	protected event OnInitialize()
	{
		var data : inkGameNotificationData;
		data = new inkGameNotificationData;
		data.notificationName = 'Test';
		token = ShowGameNotification( data );
		token.RegisterListener( this, 'OnResponse' );
	}

	protected event OnResponse( data : inkGameNotificationData )
	{
		token = NULL;
	}

}

class gameNotificationsReceiverTest extends inkGameController
{
	var token : inkGameNotificationToken;

	protected event OnInitialize()
	{
		var data : inkGameNotificationData;
		var customData : customGameNotificationDataSet;
		data = ( ( inkGameNotificationData )( GetRootWidget().GetUserData( 'inkGameNotificationData' ) ) );
		customData = new customGameNotificationDataSet;
		customData.customText = 'game notification test text';
		customData.testBool = true;
		data.token.TriggerCallback( customData );
	}

}

