class Ladder extends InteractiveDevice
{
	default m_controllerTypeName = 'LadderController';

	protected event OnRequestComponents( ri : EntityRequestComponentsInterface )
	{
		super.OnRequestComponents( ri );
	}

	protected event OnTakeControl( ri : EntityResolveComponentsInterface )
	{
		super.OnTakeControl( ri );
		m_controller = ( ( LadderController )( EntityResolveComponentsInterface.GetComponent( ri, 'controller' ) ) );
	}

	protected const override function HasAnyDirectInteractionActive() : Bool
	{
		return true;
	}

	public const override function DeterminGameplayRole() : EGameplayRole
	{
		return EGameplayRole.OpenPath;
	}

	private const override function GetController() : LadderController
	{
		return ( ( LadderController )( m_controller ) );
	}

	public const override function GetDevicePS() : LadderControllerPS
	{
		return GetController().GetPS();
	}

}

