class StaticPlatformController extends ScriptableDeviceComponent
{

	public const override function GetPS() : StaticPlatformControllerPS
	{
		return ( ( StaticPlatformControllerPS )( GetBasePS() ) );
	}

}

class StaticPlatformControllerPS extends ScriptableDeviceComponentPS
{
	private persistent var m_isTriggered : Bool;

	public function IsTriggered() : Bool
	{
		return m_isTriggered;
	}

	public function SetAsTriggered()
	{
		m_isTriggered = true;
	}

}

