class VirtualMasterDevice extends Device
{
}

class VirtualMasterDevicePS extends ScriptableDeviceComponentPS
{
	var m_owner : IScriptable;
	var m_globalActions : array< DeviceAction >;
	protected persistent var m_context : GetActionsContext;
	var m_connectedDevices : array< DeviceComponentPS >;

	public virtual function InitializeVirtualDevice()
	{
		SetDeviceState( EDeviceStatus.ON );
		Initialize();
	}

	protected virtual function DoCustomShit( const devices : ref< array< DeviceComponentPS > >, on : Bool ) {}

	protected virtual function GetGlobalActions( actions : ref< array< DeviceAction > > ) {}
}

