class HubExperienceBarController extends inkLogicController
{
	protected editable var m_foregroundContainer : inkWidgetRef;

	public function SetValue( value : Int32, maxValue : Int32 )
	{
		SetValueF( ( ( Float )( value ) ), ( ( Float )( maxValue ) ) );
	}

	public function SetValueF( value : Float, maxValue : Float )
	{
		inkWidgetRef.SetScale( m_foregroundContainer, Vector2( value / maxValue, 1.0 ) );
	}

}

