class TimeSkipFinishEvent extends Event
{
}

class MenuScenario_TimeSkip extends MenuScenario_BaseMenu
{

	protected event OnEnterScenario( prevScenario : CName, userData : IScriptable )
	{
		GetMenusState().OpenMenu( 'time_skip' );
		SetCursorVisibility( true );
	}

	protected event OnTimeSkipPopupClosed()
	{
		SetCursorVisibility( false );
		GotoIdleState();
	}

	private function SetCursorVisibility( visible : Bool )
	{
		var evt : inkMenuLayer_SetCursorVisibility;
		evt = new inkMenuLayer_SetCursorVisibility;
		evt.Init( visible );
		QueueEvent( evt );
	}

}

