class MeleePreAttackExecutor extends EffectExecutor_Scripted
{

	public function Process( ctx : EffectScriptContext, applierCtx : EffectExecutionScriptContext ) : Bool
	{
		var target : Entity;
		var targetID : EntityID;
		var aiEvent : StimuliEvent;
		target = EffectExecutionScriptContext.GetTarget( applierCtx );
		if( target )
		{
			targetID = target.GetEntityID();
			aiEvent = new StimuliEvent;
			aiEvent.name = 'MeleeDodgeOpportunity';
			target.QueueEventForEntityID( targetID, aiEvent );
			return true;
		}
		else
		{
			return false;
		}
	}

}

