class CharacterCreationSummaryListItemData extends IScriptable
{
	var label : String;
	var desc : String;
}

class characterCreationSummaryListItem extends ListItemController
{
	editable var m_headerLabel : inkTextRef;
	editable var m_descLabel : inkTextRef;
	var m_data : CharacterCreationSummaryListItemData;

	protected event OnInitialize() {}

	public function Refresh( newData : IScriptable )
	{
		m_data = ( ( CharacterCreationSummaryListItemData )( newData ) );
		inkTextRef.SetText( m_headerLabel, m_data.label );
		inkTextRef.SetText( m_descLabel, m_data.desc );
	}

}

