importonly struct TutorialBracketData
{
	import var bracketID : CName;
	import var bracketType : gameTutorialBracketType;
	import var anchor : inkEAnchor;
	import var offset : Vector2;
	import var size : Vector2;
}

import class TutorialArea extends inkLogicController
{
}

import class TutorialBracketLogicController extends inkLogicController
{
	private var m_loopAnim : inkAnimProxy;

	private export function PlayShowAnimation() : inkAnimProxy
	{
		var anim : inkAnimProxy;
		anim = PlayLibraryAnimation( 'BracketShow' );
		if( anim != NULL )
		{
			anim.RegisterToCallback( inkanimEventType.OnFinish, this, 'OnShowFinished' );
		}
		return anim;
	}

	private export function PlayHideAnimation() : inkAnimProxy
	{
		if( m_loopAnim )
		{
			m_loopAnim.Stop();
		}
		return PlayLibraryAnimation( 'BracketHide' );
	}

	protected event OnShowFinished( e : inkAnimProxy )
	{
		var options : inkAnimOptions;
		options.loopType = inkanimLoopType.Cycle;
		options.loopInfinite = true;
		m_loopAnim = PlayLibraryAnimation( 'BracketLoop', options );
	}

}

import enum gameTutorialBracketType
{
	WidgetArea,
	CustomArea,
}

