enum ETelemetryData
{
	MeleeAttacksMade = 0,
	RangedAttacksMade = 1,
	BluelinesSelected = 2,
	MeleeKills = 3,
	RangedKills = 4,
	QuickHacksMade = 5,
	LegendaryItemsCrafted = 6,
}

enum ENPCTelemetryData
{
	HitByLightAttack = 0,
	HitByStrongAttack = 1,
	HitByFinalComboAttack = 2,
	HitByBlockAttack = 3,
	BlockedAttack = 4,
	DeflectedAttack = 5,
	WasGuardBreaked = 6,
}

enum EDownedType
{
	Killed = 0,
	Finished = 1,
	Defeated = 2,
	Unconscious = 3,
}

class DataTrackingSystem extends ScriptableSystem
{
	protected persistent var m_achievementEnumKeyMap : array< Int32 >;
	protected persistent var m_achievementsMask : array< Bool >;
	protected persistent var m_rangedAttacksMade : Int32;
	protected persistent var m_meleeAttacksMade : Int32;
	protected persistent var m_meleeKills : Int32;
	protected persistent var m_rangedKills : Int32;
	protected persistent var m_quickhacksMade : Int32;
	protected persistent var m_distractionsMade : Int32;
	protected persistent var m_legendaryItemsCrafted : Int32;
	protected persistent var m_npcMeleeLightAttackReceived : Int32;
	protected persistent var m_npcMeleeStrongAttackReceived : Int32;
	protected persistent var m_npcMeleeBlockAttackReceived : Int32;
	protected persistent var m_npcMeleeBlockedAttacks : Int32;
	protected persistent var m_npcMeleeDeflectedAttacks : Int32;
	protected persistent var m_downedEnemies : Int32;
	protected persistent var m_killedEnemies : Int32;
	protected persistent var m_defeatedEnemies : Int32;
	protected persistent var m_incapacitatedEnemies : Int32;
	protected persistent var m_finishedEnemies : Int32;
	protected persistent var m_downedWithRanged : Int32;
	protected persistent var m_downedWithMelee : Int32;
	protected persistent var m_downedInTimeDilatation : Int32;
	protected persistent var m_rangedProgress : Int32;
	protected persistent var m_meleeProgress : Int32;
	protected persistent var m_dilationProgress : Int32;
	protected persistent var m_failedShardDrops : Float;
	protected persistent var m_LegPlusPlusHackDropped : Bool;
	protected persistent var m_bluelinesUseCount : Int32;
	private var m_twoHeadssourceID : EntityID;
	private var m_twoHeadsValidTimestamp : Float;
	private var m_lastKillTimestamp : Float;
	private var m_enemiesKilledInTimeInterval : array< weak< GameObject > >;
	private var m_timeInterval : Float;
	default m_timeInterval = 5f;
	private var m_numerOfKillsRequired : Int32;
	default m_numerOfKillsRequired = 3f;
	private var m_gunKataKilledEnemies : Int32;
	private var m_gunKataValidTimestamp : Float;
	private var m_hardKneesInProgress : Bool;
	private var m_hardKneesKilledEnemies : Int32;
	private var m_harKneesValidTimestamp : Float;
	private var m_resetKilledReqDelayID : DelayID;
	private var m_resetFinishedReqDelayID : DelayID;
	private var m_resetDefeatedReqDelayID : DelayID;
	private var m_resetIncapacitatedReqDelayID : DelayID;
	private var m_resetDownedReqDelayID : DelayID;
	private var m_resetMeleeAttackReqDelayID : DelayID;
	private var m_resetRangedAttackReqDelayID : DelayID;
	private var m_resetAttackReqDelayID : DelayID;
	private var m_resetNpcMeleeLightAttackReqDelayID : DelayID;
	private var m_resetNpcMeleeStrongAttackReqDelayID : DelayID;
	private var m_resetNpcMeleeFinalAttackReqDelayID : DelayID;
	private var m_resetNpcMeleeBlockAttackReqDelayID : DelayID;
	private var m_resetNpcBlockedReqDelayID : DelayID;
	private var m_resetNpcDeflectedReqDelayID : DelayID;
	private var m_resetNpcGuardbreakReqDelayID : DelayID;

	private export override function OnAttach()
	{
		var i : Int32;
		var size : Int32;
		size = ( ( Int32 )( gamedataAchievement.Count ) );
		if( m_achievementEnumKeyMap.Size() < size )
		{
			for( i = m_achievementEnumKeyMap.Size(); i < size; i += 1 )
			{
				m_achievementEnumKeyMap.PushBack( -1 );
			}
			for( i = 0; i < size; i += 1 )
			{
				m_achievementEnumKeyMap[ i ] = GetAchievementKeyFromRecord( ( ( gamedataAchievement )( i ) ) );
			}
		}
		if( m_achievementsMask.Size() < size )
		{
			for( i = m_achievementsMask.Size(); i < size; i += 1 )
			{
				m_achievementsMask.PushBack( false );
			}
		}
	}

	private export override function OnDetach() {}

	private export override function OnRestored( saveVersion : Int32, gameVersion : Int32 )
	{
		var factVal : Int32;
		factVal = GetFact( GetGameInstance(), 'AchievementEP1Fix' );
		if( factVal <= 0 )
		{
			ValidateAchievements();
			SendAllUnlockAchievemntRequests();
			SetFactValue( GetGameInstance(), 'AchievementEP1Fix', 1 );
		}
	}

	private function ValidateAchievements()
	{
		SetFlag( gamedataAchievement.Roleplayer, IsValidRoleplayerAchievement() );
		SetFlag( gamedataAchievement.MustBeTheRats, IsValidMustBeTheRatsAchievement() );
		SetFlag( gamedataAchievement.HandyMan, IsValidHandyManAchievement() );
		SetFlag( gamedataAchievement.MaxPain, IsValidMaxPainAchievement() );
		SetFlag( gamedataAchievement.TrueWarrior, IsValidTrueWarriorAchievement() );
		SetFlag( gamedataAchievement.TrueSoldier, IsValidTrueSoldierAchievement() );
	}

	private const function SendAllUnlockAchievemntRequests()
	{
		var i, limit : Int32;
		var achievementRequest : AddAchievementRequest;
		for( i = 0, limit = m_achievementsMask.Size(); i < limit; i += 1 )
		{
			if( m_achievementsMask[ i ] == true )
			{
				achievementRequest = new AddAchievementRequest;
				achievementRequest.achievement = GetAchievementFromKey( i );
				QueueRequest( achievementRequest );
			}
		}
	}

	private const function GetAchievementKeyFromRecord( achievement : gamedataAchievement ) : Int32
	{
		var achievementRecord : weak< Achievement_Record >;
		achievementRecord = GetAchievementRecordFromGameDataAchievement( achievement );
		return achievementRecord.PS4Key();
	}

	private const function GetAchievementFromKey( key : Int32 ) : gamedataAchievement
	{
		var i : Int32;
		for( i = 0; i < m_achievementEnumKeyMap.Size(); i += 1 )
		{
			if( key == m_achievementEnumKeyMap[ i ] )
			{
				return ( ( gamedataAchievement )( i ) );
			}
		}
		return gamedataAchievement.Invalid;
	}

	private function AddFlag( achievement : gamedataAchievement )
	{
		m_achievementsMask[ m_achievementEnumKeyMap[ ( ( Int32 )( achievement ) ) ] ] = true;
	}

	private function SetFlag( achievement : gamedataAchievement, value : Bool )
	{
		m_achievementsMask[ m_achievementEnumKeyMap[ ( ( Int32 )( achievement ) ) ] ] = value;
	}

	private function GetNameFromDataTrackingFactEnum( dataTrackingFact : ETelemetryData ) : CName
	{
		return EnumValueToName( 'EDataTrackingFact', ( ( Int32 )( dataTrackingFact ) ) );
	}

	private function GetCountFromDataTrackingFactEnum( dataTrackingFact : ETelemetryData ) : Int32
	{
		return GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( GetNameFromDataTrackingFactEnum( dataTrackingFact ) );
	}

	private const function IsValidRoleplayerAchievement() : Bool
	{
		return m_bluelinesUseCount >= 10;
	}

	private const function IsValidMustBeTheRatsAchievement() : Bool
	{
		return m_quickhacksMade >= 30;
	}

	private export function OnModifyTelemetryVariable( request : ModifyTelemetryVariable )
	{
		switch( request.dataTrackingFact )
		{
			case ETelemetryData.MeleeAttacksMade:
			{
				m_meleeAttacksMade += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_player_melee_attacks', m_meleeAttacksMade );
				SetFactValue( GetGameInstance(), 'gmpl_player_melee_attack', 1 );
				GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetMeleeAttackReqDelayID );
				m_resetMeleeAttackReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetMeleeAttackDelayedRequest, 1.0 );
				break;
			}
			case ETelemetryData.RangedAttacksMade:
			{
				m_rangedAttacksMade += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_player_range_attacks', m_rangedAttacksMade );
				SetFactValue( GetGameInstance(), 'gmpl_player_range_attack', 1 );
				GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetRangedAttackReqDelayID );
				m_resetRangedAttackReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetRangedAttackDelayedRequest, 1.0 );
				break;
			}
			case ETelemetryData.BluelinesSelected:
			{
				m_bluelinesUseCount += request.value;
				if( !( IsAchievementUnlocked( gamedataAchievement.Roleplayer ) ) )
				{
					SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.Roleplayer ), m_bluelinesUseCount, 10 );
				}
				ProcessIntCompareAchievement( gamedataAchievement.Roleplayer, m_bluelinesUseCount, 10 );
				break;
			}
			case ETelemetryData.QuickHacksMade:
			{
				m_quickhacksMade += request.value;
				if( !( IsAchievementUnlocked( gamedataAchievement.MustBeTheRats ) ) )
				{
					SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.MustBeTheRats ), m_quickhacksMade, 30 );
				}
				ProcessIntCompareAchievement( gamedataAchievement.MustBeTheRats, m_quickhacksMade, 30 );
				SetFactValue( GetGameInstance(), 'gmpl_player_quickhacks', m_quickhacksMade );
				SetFactValue( GetGameInstance(), 'gmpl_player_quickhack', 1 );
				GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetAttackReqDelayID );
				m_resetAttackReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetAttackDelayedRequest, 1.0 );
				break;
			}
		}
		if( request.dataTrackingFact != ETelemetryData.QuickHacksMade )
		{
			SetFactValue( GetGameInstance(), 'gmpl_player_attacks', ( m_meleeAttacksMade + m_rangedAttacksMade ) + m_quickhacksMade );
			SetFactValue( GetGameInstance(), 'gmpl_player_attack', 1 );
			GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetKilledReqDelayID );
			m_resetKilledReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCKilledDelayedRequest, 1.0 );
		}
		ProcessTutorialFact( request.dataTrackingFact );
	}

	private export function OnModifyNPCTelemetryVariable( request : ModifyNPCTelemetryVariable )
	{
		switch( request.dataTrackingFact )
		{
			case ENPCTelemetryData.HitByLightAttack:
			{
				m_npcMeleeLightAttackReceived += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_lights', GetFact( GetGameInstance(), 'gmpl_npc_hit_by_melee_lights' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.HitByStrongAttack:
			{
				m_npcMeleeStrongAttackReceived += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_strongs', GetFact( GetGameInstance(), 'gmpl_npc_hit_by_melee_strongs' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.HitByFinalComboAttack:
			{
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_combofinal', GetFact( GetGameInstance(), 'gmpl_npc_hit_by_melee_combofinal' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.HitByBlockAttack:
			{
				m_npcMeleeBlockAttackReceived += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_blockattacks', GetFact( GetGameInstance(), 'gmpl_npc_hit_by_melee_blockattacks' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.BlockedAttack:
			{
				m_npcMeleeBlockedAttacks += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_npc_blocked_attacks', GetFact( GetGameInstance(), 'gmpl_npc_blocked_attacks' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.DeflectedAttack:
			{
				m_npcMeleeDeflectedAttacks += request.value;
				SetFactValue( GetGameInstance(), 'gmpl_npc_deflected_attacks', GetFact( GetGameInstance(), 'gmpl_npc_deflected_attacks' ) + 1 );
				SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 1 );
				break;
			}
			case ENPCTelemetryData.WasGuardBreaked:
			{
				SetFactValue( GetGameInstance(), 'gmpl_npc_guardbreak', GetFact( GetGameInstance(), 'gmpl_npc_guardbreak' ) + 1 );
				break;
			}
		}
	}

	private function ProcessTutorialFact( telemetryData : ETelemetryData )
	{
		switch( telemetryData )
		{
			case ETelemetryData.MeleeAttacksMade:
			{
				if( ( GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( 'melee_combat_tutorial' ) == 0 ) && ( GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( 'disable_tutorials' ) == 0 ) )
				{
					GameInstance.GetQuestsSystem( GetGameInstance() ).SetFact( 'melee_combat_tutorial', 1 );
				}
				break;
			}
			case ETelemetryData.RangedAttacksMade:
			{
				if( ( ( GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( 'ranged_combat_tutorial' ) == 0 ) && ( GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( 'block_combat_scripts_tutorials' ) == 0 ) ) && ( GameInstance.GetQuestsSystem( GetGameInstance() ).GetFact( 'disable_tutorials' ) == 0 ) )
				{
					GameInstance.GetQuestsSystem( GetGameInstance() ).SetFact( 'ranged_combat_tutorial', 1 );
				}
				break;
			}
		}
	}

	private export function OnAddAchievementRequest( request : AddAchievementRequest )
	{
		UnlockAchievement( GetAchievementRecordFromGameDataAchievement( request.achievement ) );
	}

	private export function OnSetAchievementProgressRequest( request : SetAchievementProgressRequest )
	{
		SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( request.achievement ), request.currentValue, request.maxValue );
	}

	private function UnlockAchievement( achievementRecord : weak< Achievement_Record > )
	{
		AddFlag( achievementRecord.Type() );
		GameInstance.GetAchievementSystem( GetGameInstance() ).UnlockAchievement( achievementRecord );
	}

	private function SetAchievementProgress( achievementRecord : weak< Achievement_Record >, currentValue : Int32, maxValue : Int32 )
	{
		var completion : Float;
		completion = ( ( ( Float )( currentValue ) ) / ( ( Float )( maxValue ) ) ) * 100.0;
		GameInstance.GetAchievementSystem( GetGameInstance() ).SetAchievementProgress( achievementRecord, completion );
	}

	private function OnBluelineSelectedRequest( request : BluelineSelectedRequest )
	{
		var mtvRequest : ModifyTelemetryVariable;
		mtvRequest = new ModifyTelemetryVariable;
		mtvRequest.dataTrackingFact = ETelemetryData.BluelinesSelected;
		QueueRequest( mtvRequest );
	}

	private export function OnSendItemCraftedDataTrackingRequest( request : ItemCraftedDataTrackingRequest )
	{
		ProcessHandyManAchievement( request.targetItem );
	}

	private const function IsValidHandyManAchievement() : Bool
	{
		return m_legendaryItemsCrafted >= 3;
	}

	private function ProcessHandyManAchievement( targetItem : ItemID )
	{
		var gameInstance : GameInstance;
		var transactionSystem : TransactionSystem;
		var itemdata : weak< gameItemData >;
		if( IsAchievementUnlocked( gamedataAchievement.HandyMan ) )
		{
			return;
		}
		gameInstance = GetGameInstance();
		transactionSystem = GameInstance.GetTransactionSystem( gameInstance );
		itemdata = transactionSystem.GetItemData( GameInstance.GetPlayerSystem( gameInstance ).GetLocalPlayerControlledGameObject(), targetItem );
		if( !( itemdata.HasStatData( gamedataStatType.Quality ) ) )
		{
			return;
		}
		if( itemdata.GetStatValueByType( gamedataStatType.Quality ) == 4.0 )
		{
			m_legendaryItemsCrafted += 1;
			SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.HandyMan ), m_legendaryItemsCrafted, 3 );
			if( m_legendaryItemsCrafted >= 3 )
			{
				UnlockAchievement( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.HandyMan ) );
			}
		}
	}

	private function IsSourcePlayer( attackData : AttackData ) : Bool
	{
		return ( ( PlayerPuppet )( attackData.GetInstigator() ) );
	}

	private function CheckTimeDilationSources() : Bool
	{
		var timeSystem : TimeSystem;
		timeSystem = GameInstance.GetTimeSystem( GetGameInstance() );
		return ( timeSystem.IsTimeDilationActive( TimeDilationHelper.GetSandevistanKey() ) || timeSystem.IsTimeDilationActive( TimeDilationHelper.GetKerenzikovKey() ) ) || timeSystem.IsTimeDilationActive( TimeDilationHelper.GetFocusedStateKey() );
	}

	private const function IsValidMaxPainAchievement() : Bool
	{
		return m_downedInTimeDilatation >= 50;
	}

	private const function IsValidTrueWarriorAchievement() : Bool
	{
		return m_downedWithMelee >= 100;
	}

	private const function IsValidTrueSoldierAchievement() : Bool
	{
		return m_downedWithRanged >= 300;
	}

	private export function OnNPCKillDataTrackingRequest( request : NPCKillDataTrackingRequest )
	{
		var attackRecord : Attack_GameEffect_Record;
		attackRecord = ( ( Attack_GameEffect_Record )( request.damageEntry.hitEvent.attackData.GetAttackDefinition().GetRecord() ) );
		if( !( request.isDownedRecorded ) )
		{
			m_downedEnemies += 1;
			if( CheckTimeDilationSources() && IsSourcePlayer( request.damageEntry.hitEvent.attackData ) )
			{
				m_downedInTimeDilatation += 1;
				if( !( IsAchievementUnlocked( gamedataAchievement.MaxPain ) ) )
				{
					m_dilationProgress += 1;
					if( m_dilationProgress >= 2 )
					{
						SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.MaxPain ), m_downedInTimeDilatation, 50 );
						m_dilationProgress = 0;
					}
				}
				ProcessIntCompareAchievement( gamedataAchievement.MaxPain, m_downedInTimeDilatation, 50 );
			}
			if( ( ( AttackData.IsMelee( request.damageEntry.hitEvent.attackData.GetAttackType() ) || AttackData.IsThrown( request.damageEntry.hitEvent.attackData.GetAttackType() ) ) || request.damageEntry.hitEvent.attackData.GetWeapon().IsBlade() ) && IsSourcePlayer( request.damageEntry.hitEvent.attackData ) )
			{
				m_downedWithMelee += 1;
				if( !( IsAchievementUnlocked( gamedataAchievement.TrueWarrior ) ) )
				{
					m_meleeProgress += 1;
					if( m_meleeProgress >= 4 )
					{
						SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.TrueWarrior ), m_downedWithMelee, 100 );
						m_meleeProgress = 0;
					}
				}
				ProcessIntCompareAchievement( gamedataAchievement.TrueWarrior, m_downedWithMelee, 100 );
			}
			if( ( AttackData.IsRangedOrDirectOrThrown( request.damageEntry.hitEvent.attackData.GetAttackType() ) || ( AttackData.IsEffect( request.damageEntry.hitEvent.attackData.GetAttackType() ) && request.damageEntry.hitEvent.attackData.GetWeapon().IsBlade() ) ) && IsSourcePlayer( request.damageEntry.hitEvent.attackData ) )
			{
				m_downedWithRanged += 1;
				if( !( IsAchievementUnlocked( gamedataAchievement.TrueSoldier ) ) )
				{
					m_rangedProgress += 1;
					if( m_rangedProgress >= 5 )
					{
						SetAchievementProgress( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.TrueSoldier ), m_downedWithRanged, 300 );
						m_rangedProgress = 0;
					}
					ProcessIntCompareAchievement( gamedataAchievement.TrueSoldier, m_downedWithRanged, 300 );
				}
				ProcessTwoHeadsOneBulletAchievement( request );
				ProcessGunKataAchievement( request );
			}
			if( attackRecord.EffectName() == 'superheroLanding' && StatusEffectSystem.ObjectHasStatusEffectWithTag( request.damageEntry.hitEvent.attackData.GetInstigator(), 'BerserkBuff' ) )
			{
				ProcessHardForKneesAchievement();
			}
			if( request.damageEntry.hitEvent.attackData.HasFlag( hitFlag.GrenadeQuickhackExplosion ) )
			{
				ProcessNotTheMobileAchievement( request.damageEntry );
			}
		}
		switch( request.eventType )
		{
			case EDownedType.Killed:
				m_killedEnemies += 1;
			SetFactValue( GetGameInstance(), 'gmpl_npc_killed_by_player', 1 );
			GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetKilledReqDelayID );
			m_resetKilledReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCKilledDelayedRequest, 1.0 );
			break;
			case EDownedType.Finished:
				m_finishedEnemies += 1;
			SetFactValue( GetGameInstance(), 'gmpl_npc_finished_by_player', 1 );
			GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetFinishedReqDelayID );
			m_resetFinishedReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCFinishedDelayedRequest, 1.0 );
			break;
			case EDownedType.Defeated:
				m_defeatedEnemies += 1;
			SetFactValue( GetGameInstance(), 'gmpl_npc_defeated_by_player', 1 );
			GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetDefeatedReqDelayID );
			m_resetDefeatedReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCDefeatedDelayedRequest, 1.0 );
			break;
			case EDownedType.Unconscious:
				m_incapacitatedEnemies += 1;
			SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 1 );
			GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetIncapacitatedReqDelayID );
			m_resetIncapacitatedReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCIncapacitatedDelayedRequest, 1.0 );
		}
		GameInstance.GetDelaySystem( GetGameInstance() ).CancelDelay( m_resetDownedReqDelayID );
		m_resetDownedReqDelayID = GameInstance.GetDelaySystem( GetGameInstance() ).DelayScriptableSystemRequest( 'DataTrackingSystem', new ResetNPCDownedDelayedRequest, 1.0 );
		ProcessDataTrackingFacts();
	}

	private export function OnTakedownActionDataTrackingRequest( request : TakedownActionDataTrackingRequest )
	{
		switch( request.eventType )
		{
			case ETakedownActionType.Takedown:
				SetFactValue( GetGameInstance(), 'gmpl_npc_killed_by_player', 1 );
			m_killedEnemies += 1;
			break;
			case ETakedownActionType.TakedownNonLethal:
				SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 1 );
			m_incapacitatedEnemies += 1;
			break;
			case ETakedownActionType.TakedownNetrunner:
				SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 1 );
			m_incapacitatedEnemies += 1;
			break;
			case ETakedownActionType.TakedownMassiveTarget:
				SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 1 );
			m_incapacitatedEnemies += 1;
			break;
			case ETakedownActionType.AerialTakedown:
				SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 1 );
			m_incapacitatedEnemies += 1;
			break;
			case ETakedownActionType.KillTarget:
				SetFactValue( GetGameInstance(), 'gmpl_npc_killed_by_player', 1 );
			m_killedEnemies += 1;
			break;
		}
		ProcessDataTrackingFacts();
	}

	private function ProcessDataTrackingFacts()
	{
		SetFactValue( GetGameInstance(), 'gmpl_npcs_killed_by_player', m_killedEnemies );
		SetFactValue( GetGameInstance(), 'gmpl_npcs_finished_by_player', m_finishedEnemies );
		SetFactValue( GetGameInstance(), 'gmpl_npcs_defeated_by_player', m_defeatedEnemies );
		SetFactValue( GetGameInstance(), 'gmpl_npcs_incapacitated_by_player', m_incapacitatedEnemies );
		SetFactValue( GetGameInstance(), 'gmpl_npcs_downed_by_player', ( ( m_killedEnemies + m_finishedEnemies ) + m_defeatedEnemies ) + m_incapacitatedEnemies );
		SetFactValue( GetGameInstance(), 'gmpl_npc_downed_by_player', 1 );
		if( ( ( m_finishedEnemies > 0 ) || ( m_killedEnemies > 0 ) ) && ( GetFact( GetGameInstance(), 'player_killed_npc' ) == 0 ) )
		{
			SetFactValue( GetGameInstance(), 'player_killed_npc', 1 );
		}
	}

	private function ProcessNotTheMobileAchievement( const damageEntry : ref< DamageHistoryEntry > )
	{
		var i : Int32;
		var currentTime : Float;
		if( IsAchievementUnlocked( gamedataAchievement.NotTheMobile ) )
		{
			return;
		}
		currentTime = EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) );
		if( ( currentTime - m_lastKillTimestamp ) > m_timeInterval )
		{
			m_enemiesKilledInTimeInterval.Clear();
		}
		m_lastKillTimestamp = currentTime;
		for( i = 0; i < m_enemiesKilledInTimeInterval.Size(); i += 1 )
		{
			if( m_enemiesKilledInTimeInterval[ i ] == damageEntry.hitEvent.target )
			{
				return;
			}
		}
		m_enemiesKilledInTimeInterval.PushBack( damageEntry.hitEvent.target );
		if( m_enemiesKilledInTimeInterval.Size() >= m_numerOfKillsRequired )
		{
			UnlockAchievement( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.NotTheMobile ) );
		}
	}

	private function ProcessIntCompareAchievement( achievement : gamedataAchievement, trackedData : Int32, thresholdValue : Int32 )
	{
		if( !( IsAchievementUnlocked( achievement ) ) && ( trackedData >= thresholdValue ) )
		{
			UnlockAchievement( GetAchievementRecordFromGameDataAchievement( achievement ) );
		}
	}

	private const function GetAchievementRecordFromGameDataAchievement( achievement : gamedataAchievement ) : weak< Achievement_Record >
	{
		var achievementString : String;
		if( achievement == gamedataAchievement.LikeFatherLikeSon )
		{
			achievementString = "LikeFatherLIkeSon";
		}
		else
		{
			achievementString = EnumValueToString( "gamedataAchievement", ( ( Int32 )( achievement ) ) );
		}
		return TweakDBInterface.GetAchievementRecord( TDBID.Create( "Achievements." + achievementString ) );
	}

	private function ProcessTwoHeadsOneBulletAchievement( request : NPCKillDataTrackingRequest )
	{
		var damageData : DamageHistoryEntry;
		var entity : Entity;
		damageData = request.damageEntry;
		if( WeaponObject.GetWeaponType( ( ( WeaponObject )( damageData.hitEvent.attackData.GetWeapon() ) ).GetItemID() ) == gamedataItemType.Wea_SniperRifle )
		{
			entity = ( ( Entity )( damageData.hitEvent.attackData.GetInstigator() ) );
			if( ( m_twoHeadssourceID == entity.GetEntityID() ) && ( m_twoHeadsValidTimestamp >= EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) ) )
			{
				if( !( IsAchievementUnlocked( gamedataAchievement.TwoHeadsOneBullet ) ) )
				{
					UnlockAchievement( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.TwoHeadsOneBullet ) );
				}
			}
			else
			{
				m_twoHeadssourceID = entity.GetEntityID();
				m_twoHeadsValidTimestamp = EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) + 1.0;
			}
		}
	}

	private function ProcessGunKataAchievement( request : NPCKillDataTrackingRequest )
	{
		var damageData : DamageHistoryEntry;
		damageData = request.damageEntry;
		if( ( WeaponObject.GetWeaponType( ( ( WeaponObject )( damageData.hitEvent.attackData.GetWeapon() ) ).GetItemID() ) == gamedataItemType.Wea_Revolver || WeaponObject.GetWeaponType( ( ( WeaponObject )( damageData.hitEvent.attackData.GetWeapon() ) ).GetItemID() ) == gamedataItemType.Wea_Handgun ) && ( Vector4.Distance( damageData.source.GetWorldPosition(), damageData.target.GetWorldPosition() ) < 7.5 ) )
		{
			m_gunKataKilledEnemies += 1;
			if( m_gunKataValidTimestamp >= EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) )
			{
				if( !( IsAchievementUnlocked( gamedataAchievement.GunKata ) ) && ( m_gunKataKilledEnemies >= 3 ) )
				{
					UnlockAchievement( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.GunKata ) );
				}
			}
			else
			{
				m_gunKataKilledEnemies = 1;
				m_gunKataValidTimestamp = EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) + 3.5;
			}
		}
	}

	private function ProcessHardForKneesAchievement()
	{
		if( m_hardKneesInProgress )
		{
			m_hardKneesKilledEnemies += 1;
			if( m_harKneesValidTimestamp >= EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) )
			{
				if( !( IsAchievementUnlocked( gamedataAchievement.ThatIsSoHardForTheKnees ) ) && ( m_hardKneesKilledEnemies >= 2 ) )
				{
					UnlockAchievement( GetAchievementRecordFromGameDataAchievement( gamedataAchievement.ThatIsSoHardForTheKnees ) );
				}
			}
			else
			{
				m_hardKneesKilledEnemies = 0;
				m_hardKneesInProgress = false;
			}
		}
		else
		{
			m_hardKneesInProgress = true;
			m_hardKneesKilledEnemies += 1;
			m_harKneesValidTimestamp = EngineTime.ToFloat( GameInstance.GetSimTime( GetGameInstance() ) ) + 1.0;
		}
	}

	public const function IsAchievementUnlocked( achievement : gamedataAchievement ) : Bool
	{
		return m_achievementsMask[ m_achievementEnumKeyMap[ ( ( Int32 )( achievement ) ) ] ];
	}

	private function OnUpdateShardFailedDrops( request : UpdateShardFailedDropsRequest )
	{
		if( request.resetCounter )
		{
			m_failedShardDrops = 0.0;
		}
		else
		{
			m_failedShardDrops += request.newFailedAttempts;
		}
	}

	public const function GetFailedShardDrops() : Float
	{
		return m_failedShardDrops;
	}

	private function OnFirstPlusPlusLegendaryAwarded( request : FirstPlusPlusLegendaryAwardedRequest )
	{
		m_LegPlusPlusHackDropped = true;
	}

	public const function IsFirstPlusPlusLegendaryAwarded() : Bool
	{
		return m_LegPlusPlusHackDropped;
	}

	private export function OnResetKilledRequest( request : ResetNPCKilledDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_npc_killed_by_player', 0 );
	}

	private function OnResetFinishedRequest( request : ResetNPCFinishedDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_npc_finished_by_player', 0 );
	}

	private export function OnResetDefeatedRequest( request : ResetNPCDefeatedDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_npc_defeated_by_player', 0 );
	}

	private export function OnResetIncapacitatedRequest( request : ResetNPCIncapacitatedDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_npc_incapacitated_by_player', 0 );
	}

	private export function OnResetDownedRequest( request : ResetNPCDownedDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_npc_downed_by_player', 0 );
	}

	private export function OnResetMeleeAttackRequest( request : ResetMeleeAttackDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_player_melee_attack', 0 );
	}

	private export function OnResetRangedAttackRequest( request : ResetRangedAttackDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_player_range_attack', 0 );
	}

	private function OnResetQuickhackRequest( request : ResetAttackDelayedRequest )
	{
		SetFactValue( GetGameInstance(), 'gmpl_player_quickhack', 0 );
	}

	private function OnResetLightHitsReceivedRequest( request : ResetLightHitsReceivedRequest )
	{
		m_npcMeleeLightAttackReceived = 0;
		SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 0 );
	}

	private function OnResetStrongHitsReceivedRequest( request : ResetStrongHitsReceivedRequest )
	{
		m_npcMeleeStrongAttackReceived = 0;
		SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 0 );
	}

	private function OnResetFinalComboHitsReceivedRequest( request : ResetFinalComboHitsReceivedRequest )
	{
		m_npcMeleeBlockAttackReceived = 0;
		SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 0 );
	}

	private function OnResetBlockAttackHitsReceivedRequest( request : ResetBlockAttackHitsReceivedRequest )
	{
		m_npcMeleeBlockedAttacks = 0;
		SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 0 );
	}

	private function OnResetBlockedHitsRequest( request : ResetBlockedHitsRequest )
	{
		m_npcMeleeBlockedAttacks = 0;
		SetFactValue( GetGameInstance(), 'gmpl_npc_hit_by_melee_attack', 0 );
	}

	private function OnUnlockAllAchievementsRequest( request : UnlockAllAchievementsRequest )
	{
		var i : Int32;
		var achievement : gamedataAchievement;
		i = 0;
		for( i; i < ( ( Int32 )( gamedataAchievement.Count ) ); i += 1 )
		{
			achievement = ( ( gamedataAchievement )( i ) );
			if( ( achievement == gamedataAchievement.Breathtaking || achievement == gamedataAchievement.Count ) || achievement == gamedataAchievement.Invalid )
			{
				continue;
			}
			if( !( IsAchievementUnlocked( achievement ) ) )
			{
				UnlockAchievement( GetAchievementRecordFromGameDataAchievement( achievement ) );
			}
		}
	}

}

importonly class BluelineSelectedRequest extends PlayerScriptableSystemRequest
{
}

class ModifyTelemetryVariable extends PlayerScriptableSystemRequest
{
	var dataTrackingFact : ETelemetryData;
	var value : Int32;
	default value = 1;
}

class ModifyNPCTelemetryVariable extends PlayerScriptableSystemRequest
{
	var dataTrackingFact : ENPCTelemetryData;
	var value : Int32;
	default value = 1;
}

class AddAchievementRequest extends PlayerScriptableSystemRequest
{
	var achievement : gamedataAchievement;
	var achievementRecord : weak< Achievement_Record >;
}

class SetAchievementProgressRequest extends PlayerScriptableSystemRequest
{
	var achievement : gamedataAchievement;
	var currentValue : Int32;
	var maxValue : Int32;
}

class NPCKillDataTrackingRequest extends PlayerScriptableSystemRequest
{
	var eventType : EDownedType;
	var damageEntry : DamageHistoryEntry;
	var isDownedRecorded : Bool;
}

class TakedownActionDataTrackingRequest extends PlayerScriptableSystemRequest
{
	var eventType : ETakedownActionType;
}

class ItemCraftedDataTrackingRequest extends PlayerScriptableSystemRequest
{
	var targetItem : ItemID;
}

class NPCThrowingGrenadeEvent extends Event
{
	var target : weak< GameObject >;
}

class FinishedVendettaTimeEvent extends Event
{
}

class ProcessVendettaAchievementEvent extends Event
{
	var deathInstigator : weak< GameObject >;
}

class UpdateShardFailedDropsRequest extends ScriptableSystemRequest
{
	var resetCounter : Bool;
	var newFailedAttempts : Float;
}

class FirstPlusPlusLegendaryAwardedRequest extends ScriptableSystemRequest
{
}

class UnlockAllAchievementsRequest extends ScriptableSystemRequest
{
}

class ResetNPCKilledDelayedRequest extends ScriptableSystemRequest
{
}

class ResetNPCFinishedDelayedRequest extends ScriptableSystemRequest
{
}

class ResetNPCDefeatedDelayedRequest extends ScriptableSystemRequest
{
}

class ResetNPCIncapacitatedDelayedRequest extends ScriptableSystemRequest
{
}

class ResetNPCDownedDelayedRequest extends ScriptableSystemRequest
{
}

class ResetMeleeAttackDelayedRequest extends ScriptableSystemRequest
{
}

class ResetRangedAttackDelayedRequest extends ScriptableSystemRequest
{
}

class ResetAttackDelayedRequest extends ScriptableSystemRequest
{
}

class ResetLightHitsReceivedRequest extends ScriptableSystemRequest
{
}

class ResetStrongHitsReceivedRequest extends ScriptableSystemRequest
{
}

class ResetFinalComboHitsReceivedRequest extends ScriptableSystemRequest
{
}

class ResetBlockAttackHitsReceivedRequest extends ScriptableSystemRequest
{
}

class ResetBlockedHitsRequest extends ScriptableSystemRequest
{
}

class ResetDeflectedHitsRequest extends ScriptableSystemRequest
{
}

class ResetGuardBreakRequest extends ScriptableSystemRequest
{
}

struct GrenadeQuickhackKillEntry
{
	var source : weak< GameObject >;
	var targets : array< weak< GameObject > >;
	var timestamps : array< Float >;
}

class DelayedAchivementCallback extends DelayCallback
{
	protected var id : Int32;
	protected var progress : Float;
	protected var dataTrackingSystem : DataTrackingSystem;

	public static function Create( id : Int32, progress : Float, dataTrackingSystem : DataTrackingSystem ) : DelayedAchivementCallback
	{
		var callback : DelayedAchivementCallback;
		callback = new DelayedAchivementCallback;
		callback.id = id;
		callback.progress = progress;
		callback.dataTrackingSystem = dataTrackingSystem;
		return callback;
	}

	public override function Call()
	{
		var gdAchievement : gamedataAchievement;
		var evt : SetAchievementProgressRequest;
		evt = new SetAchievementProgressRequest;
		if( id == -1 )
		{
			gdAchievement = ( ( gamedataAchievement )( RandRange( 0, ( ( Int32 )( gamedataAchievement.Count ) ) ) ) );
		}
		else
		{
			gdAchievement = ( ( gamedataAchievement )( id ) );
		}
		evt.achievement = gdAchievement;
		evt.maxValue = 1000;
		evt.currentValue = ( ( Int32 )( progress * ( ( Float )( evt.maxValue ) ) ) );
		dataTrackingSystem.QueueRequest( evt );
	}

}

function ProgressMultipleAchievementsImpl( gameInstance : GameInstance, achievementId : String, achievementCount : String, baseProgressString : String, intervalString : String )
{
	var dataTrackingSystem : DataTrackingSystem;
	var delaySystem : DelaySystem;
	var id : Int32;
	var count : Float;
	var interval : Float;
	var baseProgress : Float;
	var i : Float;
	i = 0.0;
	id = StringToInt( achievementId );
	interval = StringToFloat( intervalString );
	count = ( ( Float )( StringToInt( achievementCount ) ) );
	baseProgress = StringToFloat( baseProgressString );
	dataTrackingSystem = ( ( DataTrackingSystem )( GameInstance.GetScriptableSystemsContainer( gameInstance ).Get( 'DataTrackingSystem' ) ) );
	delaySystem = GameInstance.GetDelaySystem( gameInstance );
	if( ( id < 0 ) || ( id >= ( ( Int32 )( gamedataAchievement.Count ) ) ) )
	{
		id = -1;
	}
	for( i = 0.0; i < count; i += 1.0 )
	{
		delaySystem.DelayCallback( DelayedAchivementCallback.Create( id, ( i * 0.01 ) + baseProgress, dataTrackingSystem ), i * interval, false );
	}
}

