class artist_test_area_r extends inkHUDGameController
{
	private var m_rootWidget : weak< inkWidget >;
	private var m_linesWidget : weak< inkCanvas >;

	protected event OnInitialize()
	{
		var player : PlayerPuppet;
		player = ( ( PlayerPuppet )( GetOwnerEntity() ) );
		player.RegisterInputListener( this, 'UI_DPadDown' );
		m_rootWidget = ( ( inkWidget )( GetRootWidget() ) );
		m_linesWidget = ( ( inkCanvas )( GetWidget( 'Lines' ) ) );
	}

	protected event OnAction( action : ListenerAction, consumer : ListenerActionConsumer )
	{
		if( ListenerAction.GetType( action ) == gameinputActionType.BUTTON_RELEASED )
		{
			PlayLibraryAnimationOnTargets( 'animationNameHere_1', SelectWidgets( m_rootWidget ) );
			PlayLibraryAnimationOnTargets( 'animationNameHere_2', SelectWidgets( m_linesWidget ) );
		}
	}

}

