class InitializationSoundController extends inkLogicController
{
	private editable var m_soundControlName : CName;
	private editable var m_initializeSoundName : CName;
	private editable var m_unitializeSoundName : CName;

	protected event OnInitialize()
	{
		if( m_soundControlName != '' && m_initializeSoundName != '' )
		{
			PlaySound( m_soundControlName, m_initializeSoundName );
		}
	}

	protected event OnUninitialize()
	{
		if( m_soundControlName != '' && m_unitializeSoundName != '' )
		{
			PlaySound( m_soundControlName, m_unitializeSoundName );
		}
	}

}

