class PopupStateUtils
{

	public static function SetBackgroundBlurBlendTime( gameCtrl : inkGameController, blendTime : Float )
	{
		var blackboard : IBlackboard;
		var uiSystemBB : UI_SystemDef;
		uiSystemBB = GetAllBlackboardDefs().UI_System;
		blackboard = gameCtrl.GetBlackboardSystem().Get( uiSystemBB );
		blackboard.SetFloat( uiSystemBB.CircularBlurBlendTime, blendTime );
	}

	public static function SetBackgroundBlur( gameCtrl : inkGameController, enable : Bool )
	{
		var blackboard : IBlackboard;
		var uiSystemBB : UI_SystemDef;
		uiSystemBB = GetAllBlackboardDefs().UI_System;
		blackboard = gameCtrl.GetBlackboardSystem().Get( uiSystemBB );
		blackboard.SetBool( uiSystemBB.CircularBlurEnabled, enable );
	}

}

