class AddHitFlagToAttackEffector extends ModifyAttackEffector
{
	var m_hitFlag : hitFlag;

	protected override function Initialize( record : TweakDBID, game : GameInstance, parentRecord : TweakDBID )
	{
		var str : String;
		str = TweakDBInterface.GetString( record + T".hitFlag", "" );
		m_hitFlag = ( ( hitFlag )( ( ( Int32 )( EnumValueFromString( "hitFlag", str ) ) ) ) );
	}

	protected override function Uninitialize( game : GameInstance ) {}

	private function ProcessEffector()
	{
		var hitEvent : gameHitEvent;
		hitEvent = GetHitEvent();
		if( !( hitEvent ) )
		{
			return;
		}
		hitEvent.attackData.AddFlag( m_hitFlag, 'AddHitFlagToAttackEffector' );
	}

	protected override function ActionOn( owner : GameObject )
	{
		ProcessEffector();
	}

	protected override function RepeatedAction( owner : GameObject )
	{
		ProcessEffector();
	}

}

