class ProgramTooltipController extends AGenericTooltipController
{
	protected editable var m_backgroundContainer : inkCompoundRef;
	private editable var m_nameText : inkTextRef;
	private editable var m_tierText : inkTextRef;
	private editable var m_durationWidget : inkWidgetRef;
	private editable var m_uploadTimeWidget : inkWidgetRef;
	private editable var m_cooldownWidget : inkWidgetRef;
	private editable var m_memoryCostValueText : inkTextRef;
	private editable var m_damageWrapper : inkWidgetRef;
	private editable var m_damageLabel : inkTextRef;
	private editable var m_damageValue : inkTextRef;
	private editable var m_healthPercentageLabel : inkTextRef;
	private editable var m_priceContainer : inkWidgetRef;
	private editable var m_priceText : inkTextRef;
	private editable var m_descriptionWrapper : inkWidgetRef;
	private editable var m_descriptionText : inkTextRef;
	private editable var m_hackTypeWrapper : inkWidgetRef;
	private editable var m_hackTypeText : inkTextRef;
	private editable var m_perkContainer : inkWidgetRef;
	private editable var m_perkText : inkTextRef;
	private editable var m_effectsList : inkCompoundRef;
	private editable var DEBUG_iconErrorWrapper : inkWidgetRef;
	private editable var DEBUG_iconErrorText : inkTextRef;
	private var DEBUG_showAdditionalInfo : Bool;
	private var m_data : InventoryTooltipData;
	private var m_quickHackData : InventoryTooltipData_QuickhackData;
	private var m_itemData : weak< UIInventoryItem >;
	private var m_displayContext : InventoryTooltipDisplayContext;
	private var m_itemDisplayContext : ItemDisplayContext;

	protected event OnInitialize()
	{
		super.OnInitialize();
		RegisterToGlobalInputCallback( 'OnPostOnPress', this, 'OnGlobalPress' );
		RegisterToGlobalInputCallback( 'OnPostOnRelease', this, 'OnGlobalRelease' );
	}

	protected event OnUninitialize()
	{
		UnregisterFromGlobalInputCallback( 'OnPostOnPress', this, 'OnGlobalPress' );
		UnregisterFromGlobalInputCallback( 'OnPostOnRelease', this, 'OnGlobalRelease' );
	}

	protected event OnGlobalPress( evt : inkPointerEvent )
	{
		if( evt.IsShiftDown() )
		{
			DEBUG_showAdditionalInfo = true;
		}
		else
		{
			DEBUG_showAdditionalInfo = false;
		}
		DEBUG_UpdateIconErrorInfo();
	}

	protected event OnGlobalRelease( evt : inkPointerEvent )
	{
		if( !( evt.IsShiftDown() ) )
		{
			DEBUG_showAdditionalInfo = false;
		}
		DEBUG_UpdateIconErrorInfo();
	}

	public override function SetData( tooltipData : ATooltipData )
	{
		var wrappedData : UIInventoryItemTooltipWrapper;
		if( ( ( UIInventoryItemTooltipWrapper )( tooltipData ) ) )
		{
			wrappedData = ( ( UIInventoryItemTooltipWrapper )( tooltipData ) );
			m_itemData = wrappedData.m_data;
			m_itemDisplayContext = wrappedData.m_displayContext.GetDisplayContext();
			NewRefreshUI( m_itemData, wrappedData.m_displayContext.GetPlayerAsPuppet() );
			return;
		}
		m_data = ( ( InventoryTooltipData )( tooltipData ) );
		m_quickHackData = m_data.quickhackData;
		RefreshUI();
	}

	private function NewRefreshUI( itemData : weak< UIInventoryItem >, player : weak< PlayerPuppet > )
	{
		var programData : weak< UIInventoryItemProgramData >;
		programData = itemData.GetProgramData( player, true );
		inkTextRef.SetText( m_nameText, itemData.GetName() );
		inkTextRef.SetVisible( m_nameText, m_displayContext != InventoryTooltipDisplayContext.Crafting );
		inkTextRef.SetText( m_memoryCostValueText, IntToString( programData.BaseCost ) );
		UpdateDetail( m_durationWidget, "UI-Quickhacks-DetailsDuration", programData.Duration, 0.0 );
		UpdateDetail( m_uploadTimeWidget, "UI-Quickhacks-DetailsUploadTime", programData.UploadTime, 0.0 );
		UpdateDetail( m_cooldownWidget, "UI-Quickhacks-DetailsCooldown", programData.Cooldown, 0.0 );
		inkWidgetRef.SetVisible( m_damageWrapper, false );
		NewUpdateDamage( programData );
		NewUpdateMods();
		NewUpdatePrice( player );
		NewUpdateDescription();
		NewUpdateCategory();
		NewUpdateRarity( programData );
	}

	private virtual function UpdateDetail( targetWidget : inkWidgetRef, key : String, value : Float, diff : Float )
	{
		var controller : ProgramTooltipStatController;
		controller = ( ( ProgramTooltipStatController )( inkWidgetRef.GetController( targetWidget ) ) );
		controller.SetData( GetLocalizedText( key ), value, diff );
	}

	private virtual function NewUpdateDescription()
	{
		var description : String;
		description = m_itemData.GetDescription();
		if( IsStringValid( description ) )
		{
			inkTextRef.SetText( m_descriptionText, description );
			inkWidgetRef.SetVisible( m_descriptionWrapper, true );
		}
		else
		{
			inkWidgetRef.SetVisible( m_descriptionWrapper, false );
		}
	}

	private virtual function UpdateDescription()
	{
		var description : String;
		description = m_data.description;
		if( IsStringValid( description ) )
		{
			inkTextRef.SetText( m_descriptionText, description );
			inkWidgetRef.SetVisible( m_descriptionWrapper, true );
		}
		else
		{
			inkWidgetRef.SetVisible( m_descriptionWrapper, false );
		}
	}

	private virtual function NewGetHackCategory() : weak< HackCategory_Record >
	{
		var i, limit : Int32;
		var actions : array< weak< ObjectAction_Record > >;
		var actionRecord : weak< ObjectAction_Record >;
		var hackCategory : weak< HackCategory_Record >;
		m_itemData.GetItemRecord().ObjectActions( actions );
		for( i = 0, limit = actions.Size(); i < limit; i += 1 )
		{
			actionRecord = TweakDBInterface.GetObjectActionRecord( actions[ i ].GetID() );
			hackCategory = actionRecord.HackCategory();
			if( hackCategory && hackCategory.EnumName() != 'NotAHack' )
			{
				return hackCategory;
			}
		}
		return NULL;
	}

	private virtual function NewUpdateCategory()
	{
		var hackCategory : weak< HackCategory_Record >;
		hackCategory = NewGetHackCategory();
		if( hackCategory && hackCategory.EnumName() != 'NotAHack' )
		{
			inkTextRef.SetText( m_hackTypeText, hackCategory.LocalizedDescription() );
			inkWidgetRef.SetVisible( m_hackTypeWrapper, true );
		}
		else
		{
			inkWidgetRef.SetVisible( m_hackTypeWrapper, false );
		}
	}

	private virtual function GetHackCategory() : weak< HackCategory_Record >
	{
		var i : Int32;
		var tweakRecord : weak< Item_Record >;
		var actions : array< weak< ObjectAction_Record > >;
		var actionRecord : weak< ObjectAction_Record >;
		var hackCategory : weak< HackCategory_Record >;
		tweakRecord = TDB.GetItemRecord( ItemID.GetTDBID( InventoryItemData.GetID( m_data.inventoryItemData ) ) );
		tweakRecord.ObjectActions( actions );
		for( i = 0; i < actions.Size(); i += 1 )
		{
			actionRecord = TweakDBInterface.GetObjectActionRecord( actions[ i ].GetID() );
			hackCategory = actionRecord.HackCategory();
			if( hackCategory && hackCategory.EnumName() != 'NotAHack' )
			{
				return hackCategory;
			}
		}
		return NULL;
	}

	private virtual function UpdateCategory()
	{
		var hackCategory : weak< HackCategory_Record >;
		hackCategory = GetHackCategory();
		if( hackCategory && hackCategory.EnumName() != 'NotAHack' )
		{
			inkTextRef.SetText( m_hackTypeText, hackCategory.LocalizedDescription() );
			inkWidgetRef.SetVisible( m_hackTypeWrapper, true );
		}
		else
		{
			inkWidgetRef.SetVisible( m_hackTypeWrapper, false );
		}
	}

	private function NewUpdateRarity( programData : weak< UIInventoryItemProgramData > )
	{
		var quality : CName;
		quality = UIItemsHelper.QualityEnumToName( m_itemData.GetQuality() );
		inkTextRef.SetState( m_tierText, quality );
		inkTextRef.SetState( m_nameText, quality );
		( ( inkText )( inkTextRef.Get( m_tierText ) ) ).SetText( GetLocalizedText( UIItemsHelper.QualityToLocalizationKey( m_itemData.GetQuality() ) ) );
	}

	private function UpdateRarity()
	{
		var quality : gamedataQuality;
		if( m_data.overrideRarity )
		{
			quality = UIItemsHelper.QualityNameToEnum( StringToName( m_data.quality ) );
		}
		else
		{
			quality = RPGManager.GetItemDataQuality( InventoryItemData.GetGameItemData( m_data.inventoryItemData ) );
		}
		inkTextRef.SetState( m_tierText, UIItemsHelper.QualityEnumToName( quality ) );
		inkTextRef.SetState( m_nameText, UIItemsHelper.QualityEnumToName( quality ) );
		( ( inkText )( inkTextRef.Get( m_tierText ) ) ).SetText( GetLocalizedText( UIItemsHelper.QualityToLocalizationKey( quality ) ) );
	}

	private virtual function RefreshUI()
	{
		inkTextRef.SetText( m_nameText, m_data.itemName );
		inkTextRef.SetVisible( m_nameText, m_data.displayContext != InventoryTooltipDisplayContext.Crafting );
		inkTextRef.SetText( m_memoryCostValueText, IntToString( m_data.quickhackData.baseCost ) );
		UpdateDetail( m_durationWidget, "UI-Quickhacks-DetailsDuration", m_data.quickhackData.duration, m_data.quickhackData.durationDiff );
		UpdateDetail( m_uploadTimeWidget, "UI-Quickhacks-DetailsUploadTime", m_data.quickhackData.uploadTime, m_data.quickhackData.uploadTimeDiff );
		UpdateDetail( m_cooldownWidget, "UI-Quickhacks-DetailsCooldown", m_data.quickhackData.cooldown, m_data.quickhackData.cooldownDiff );
		inkWidgetRef.SetVisible( m_damageWrapper, false );
		UpdateDamage();
		UpdateMods();
		UpdatePrice();
		UpdateDescription();
		UpdateCategory();
		UpdateRarity();
		UpdatePerkRequirement();
		DEBUG_UpdateIconErrorInfo();
		inkCompoundRef.SetVisible( m_backgroundContainer, m_data.displayContext != InventoryTooltipDisplayContext.Crafting );
	}

	private function DEBUG_UpdateIconErrorInfo()
	{
		var resultText : String;
		var errorData : DEBUG_IconErrorInfo;
		var iconsNameResolver : IconsNameResolver;
		iconsNameResolver = IconsNameResolver.GetIconsNameResolver();
		if( !( iconsNameResolver.IsInDebugMode() ) )
		{
			inkWidgetRef.SetVisible( DEBUG_iconErrorWrapper, false );
			return;
		}
		errorData = m_data.DEBUG_iconErrorInfo;
		inkWidgetRef.SetVisible( DEBUG_iconErrorWrapper, ( errorData != NULL ) || DEBUG_showAdditionalInfo );
		if( DEBUG_showAdditionalInfo )
		{
			resultText += " - itemID:\n";
			resultText += TDBID.ToStringDEBUG( ItemID.GetTDBID( InventoryItemData.GetID( m_data.inventoryItemData ) ) );
			inkTextRef.SetText( DEBUG_iconErrorText, resultText );
		}
		else
		{
			if( errorData != NULL )
			{
				resultText += ( ( "   ErrorType: " + EnumValueToString( "inkIconResult", ( ( Int32 )( errorData.errorType ) ) ) ) + "\n\n" );
				resultText += " - itemID:\n";
				resultText += errorData.itemName;
				if( errorData.isManuallySet )
				{
					resultText += "\n - resolved icon name (manually set):\n";
				}
				else
				{
					resultText += "\n - resolved icon name (auto generated):\n";
				}
				resultText += errorData.resolvedIconName;
				resultText += "\n - error message:\n";
				resultText += errorData.errorMessage;
				inkTextRef.SetText( DEBUG_iconErrorText, resultText );
			}
		}
	}

	private function IsDamageStat( targetStat : gamedataStatType, valueStat : gamedataStatType ) : Bool
	{
		if( targetStat == gamedataStatType.Invalid )
		{
			switch( valueStat )
			{
				case gamedataStatType.BaseDamage:
				case gamedataStatType.PhysicalDamage:
				case gamedataStatType.ChemicalDamage:
				case gamedataStatType.ElectricDamage:
				case gamedataStatType.ThermalDamage:
					return true;
				default:
					return false;
			}
		}
		else
		{
			return targetStat == gamedataStatType.Health;
		}
		return false;
	}

	private function NewUpdateDamage( programData : weak< UIInventoryItemProgramData > )
	{
		var i, limit : Int32;
		var effect : DamageEffectUIEntry;
		var valueToDisplay : String;
		var isHealthPercentageStat : Bool;
		for( i = 0, limit = programData.AttackEffects.Size(); i < limit; i += 1 )
		{
			effect = programData.AttackEffects[ i ];
			if( !( IsDamageStat( effect.targetStat, effect.valueStat ) ) )
			{
				continue;
			}
			isHealthPercentageStat = effect.targetStat == gamedataStatType.Health;
			inkTextRef.SetVisible( m_healthPercentageLabel, isHealthPercentageStat );
			if( isHealthPercentageStat )
			{
				valueToDisplay = "-";
			}
			valueToDisplay += IntToString( CeilF( effect.valueToDisplay ) );
			if( isHealthPercentageStat )
			{
				valueToDisplay += "%";
			}
			if( effect.isContinuous )
			{
				valueToDisplay += ( "/" + GetLocalizedText( "UI-Quickhacks-Seconds" ) );
			}
			inkTextRef.SetText( m_damageValue, valueToDisplay );
			inkTextRef.SetText( m_damageLabel, UILocalizationHelper.GetStatNameLockey( RPGManager.GetStatRecord( effect.valueStat ) ) );
			inkWidgetRef.SetVisible( m_damageWrapper, true );
			break;
		}
	}

	private function UpdateDamage()
	{
		var i : Int32;
		var effect : DamageEffectUIEntry;
		var valueToDisplay : String;
		var isHealthPercentageStat : Bool;
		for( i = 0; i < m_data.quickhackData.attackEffects.Size(); i += 1 )
		{
			effect = m_data.quickhackData.attackEffects[ i ];
			if( !( IsDamageStat( effect.targetStat, effect.valueStat ) ) )
			{
				continue;
			}
			isHealthPercentageStat = effect.targetStat == gamedataStatType.Health;
			inkTextRef.SetVisible( m_healthPercentageLabel, isHealthPercentageStat );
			if( isHealthPercentageStat )
			{
				valueToDisplay = "-";
			}
			valueToDisplay += IntToString( CeilF( effect.valueToDisplay ) );
			if( isHealthPercentageStat )
			{
				valueToDisplay += "%";
			}
			if( effect.isContinuous )
			{
				valueToDisplay += ( "/" + GetLocalizedText( "UI-Quickhacks-Seconds" ) );
			}
			inkTextRef.SetText( m_damageValue, valueToDisplay );
			inkTextRef.SetText( m_damageLabel, UILocalizationHelper.GetStatNameLockey( RPGManager.GetStatRecord( effect.valueStat ) ) );
			inkWidgetRef.SetVisible( m_damageWrapper, true );
			break;
		}
	}

	private function NewUpdateMods()
	{
		var i, limit : Int32;
		var controller : ItemTooltipModController;
		var modsManager : weak< UIInventoryItemModsManager >;
		modsManager = m_itemData.GetModsManager();
		limit = modsManager.GetModsSize();
		if( limit > 0 )
		{
			while( inkCompoundRef.GetNumChildren( m_effectsList ) > 0 )
			{
				inkCompoundRef.RemoveChildByIndex( m_effectsList, 0 );
			}
			while( inkCompoundRef.GetNumChildren( m_effectsList ) < limit )
			{
				SpawnFromLocal( inkCompoundRef.Get( m_effectsList ), 'programTooltipEffect' );
			}
			for( i = 0; i < limit; i += 1 )
			{
				controller = ( ( ItemTooltipModController )( inkCompoundRef.GetWidgetByIndex( m_effectsList, i ).GetController() ) );
				controller.SetData( modsManager.GetMod( i ) );
			}
		}
	}

	private function UpdateMods()
	{
		var i : Int32;
		var attachment : InventoryItemAttachments;
		var controller : ItemTooltipModController;
		if( m_data.itemAttachments.Size() > 0 )
		{
			while( inkCompoundRef.GetNumChildren( m_effectsList ) > 0 )
			{
				inkCompoundRef.RemoveChildByIndex( m_effectsList, 0 );
			}
			while( inkCompoundRef.GetNumChildren( m_effectsList ) < m_data.itemAttachments.Size() )
			{
				SpawnFromLocal( inkCompoundRef.Get( m_effectsList ), 'programTooltipEffect' );
			}
			for( i = 0; i < m_data.itemAttachments.Size(); i += 1 )
			{
				attachment = m_data.itemAttachments[ i ];
				controller = ( ( ItemTooltipModController )( inkCompoundRef.GetWidgetByIndex( m_effectsList, i ).GetController() ) );
				controller.SetData( attachment );
			}
		}
		else if( ( m_data.itemAttachments.Size() == 0 ) && ( m_data.specialAbilities.Size() > 0 ) )
		{
			while( inkCompoundRef.GetNumChildren( m_effectsList ) > 0 )
			{
				inkCompoundRef.RemoveChildByIndex( m_effectsList, 0 );
			}
			while( inkCompoundRef.GetNumChildren( m_effectsList ) < m_data.specialAbilities.Size() )
			{
				SpawnFromLocal( inkCompoundRef.Get( m_effectsList ), 'programTooltipEffect' );
			}
			for( i = 0; i < m_data.specialAbilities.Size(); i += 1 )
			{
				controller = ( ( ItemTooltipModController )( inkCompoundRef.GetWidgetByIndex( m_effectsList, i ).GetController() ) );
				controller.SetData( m_data.specialAbilities[ i ] );
			}
		}
		else
		{
		}
	}

	private function NewUpdatePrice( player : weak< PlayerPuppet > )
	{
		if( m_itemDisplayContext == ItemDisplayContext.Vendor )
		{
			inkTextRef.SetText( m_priceText, IntToString( RoundF( m_itemData.GetBuyPrice() ) * m_itemData.GetQuantity() ) );
		}
		else
		{
			inkTextRef.SetText( m_priceText, IntToString( RoundF( m_itemData.GetSellPrice() ) * m_itemData.GetQuantity() ) );
		}
		inkWidgetRef.SetVisible( m_priceContainer, true );
	}

	private function UpdatePrice()
	{
		if( m_data.isVendorItem )
		{
			inkTextRef.SetText( m_priceText, FloatToStringPrec( m_data.buyPrice, 0 ) );
		}
		else
		{
			inkTextRef.SetText( m_priceText, FloatToStringPrec( m_data.price, 0 ) );
		}
		inkWidgetRef.SetVisible( m_priceContainer, true );
	}

	private function UpdatePerkRequirement()
	{
		var textParams : inkTextParams;
		inkWidgetRef.SetVisible( m_perkContainer, false );
		if( m_data.isPerkRequired )
		{
			textParams = new inkTextParams;
			textParams.AddLocalizedString( "perkName", m_data.perkRequiredName );
			inkWidgetRef.SetVisible( m_perkContainer, true );
			inkTextRef.SetLocalizedTextScript( m_perkText, "LocKey#42796", textParams );
		}
	}

}

class ProgramTooltipEffectController extends ItemTooltipModController
{

	private override function EntryWidgetToSpawn() : CName
	{
		return 'programTooltipEffectEntry';
	}

}

class ProgramTooltipStatController extends inkLogicController
{
	private editable var m_arrow : inkImageRef;
	private editable var m_value : inkTextRef;
	private editable var m_diffValue : inkTextRef;

	public function SetData( localizedKey : String, value : Float, diff : Float )
	{
		if( AbsF( value ) > 0.01 )
		{
			GetRootWidget().SetState( 'Default' );
			if( value > 0.01 )
			{
				inkTextRef.SetText( m_value, ( ( ( localizedKey + " " ) + FloatToStringPrec( value, 2 ) ) + " " ) + GetLocalizedText( "UI-Quickhacks-Seconds" ) );
			}
			else
			{
				inkTextRef.SetText( m_value, ( localizedKey + " " ) + GetLocalizedText( "UI-Quickhacks-Infinite" ) );
			}
		}
		else
		{
			GetRootWidget().SetState( 'Empty' );
			inkTextRef.SetText( m_value, ( localizedKey + " " ) + GetLocalizedText( "UI-Quickhacks-NotApplicable" ) );
		}
		UpdateComparedValue( diff );
	}

	private function UpdateComparedValue( diffValue : Float )
	{
		var isVisible : Bool;
		var comaredStatText : String;
		var statToSet : CName;
		isVisible = diffValue != 0.0;
		statToSet = ( ( diffValue > 0.0 ) ? ( 'Better' ) : ( 'Worse' ) );
		comaredStatText += ( ( ( diffValue > 0.0 ) ) ? ( "+" ) : ( "-" ) );
		comaredStatText += FloatToStringPrec( AbsF( diffValue ), 2 );
		inkTextRef.SetText( m_diffValue, comaredStatText );
		inkImageRef.SetVisible( m_arrow, isVisible );
		inkTextRef.SetVisible( m_diffValue, isVisible );
		inkImageRef.SetState( m_arrow, statToSet );
		inkTextRef.SetState( m_diffValue, statToSet );
		inkImageRef.SetBrushMirrorType( m_arrow, ( ( diffValue > 0.0 ) ? ( inkBrushMirrorType.NoMirror ) : ( inkBrushMirrorType.Vertical ) ) );
	}

}

