class EquipPrimaryWeaponCommandDelegate extends ScriptBehaviorDelegate
{
	editable inlined var command : weak< AISwitchToPrimaryWeaponCommand >;
	editable inlined var unEquip : Bool;

	public function DoSetupCommand() : Bool
	{
		unEquip = command.unEquip;
		return true;
	}

	public function DoEndCommand() : Bool
	{
		unEquip = false;
		return true;
	}

}

class EquipSecondaryWeaponCommandDelegate extends ScriptBehaviorDelegate
{
	editable inlined var command : weak< AISwitchToSecondaryWeaponCommand >;
	editable inlined var unEquip : Bool;

	public function DoSetupCommand() : Bool
	{
		unEquip = command.unEquip;
		return true;
	}

	public function DoEndCommand() : Bool
	{
		unEquip = false;
		return true;
	}

}

