class RootMotionCommandHandler extends AICommandHandlerBase
{
	protected editable inlined var m_params : AIArgumentMapping;

	protected override function UpdateCommand( context : ScriptExecutionContext, command : AICommand ) : AIbehaviorUpdateOutcome
	{
		var typedCommand : AIRootMotionCommand;
		typedCommand = ( ( AIRootMotionCommand )( command ) );
		if( !( typedCommand ) )
		{
			LogAIError( ( "Argument 'inCommand' has invalid type. Expected AIRootMotionCommand, got " + ( ( String )( command.GetClassName() ) ) ) + "." );
			return AIbehaviorUpdateOutcome.FAILURE;
		}
		if( !( m_params ) )
		{
			LogAIError( "Argument 'params' is null. Cannot set motion params." );
			return AIbehaviorUpdateOutcome.FAILURE;
		}
		ScriptExecutionContext.SetMappingValue( context, m_params, typedCommand.params );
		return AIbehaviorUpdateOutcome.SUCCESS;
	}

}

