class UseWorkspotCommandDelegate extends ScriptBehaviorDelegate
{
	editable inlined var m_inCommand : AIArgumentMapping;
	var movementType : moveMovementType;

	public export function DoSetupUseWorkspotCommand( context : ScriptExecutionContext ) : Bool
	{
		var rawCommand : IScriptable;
		var typedCommand : AIBaseUseWorkspotCommand;
		if( m_inCommand )
		{
			rawCommand = ScriptExecutionContext.GetScriptableMappingValue( context, m_inCommand );
			typedCommand = ( ( AIBaseUseWorkspotCommand )( rawCommand ) );
		}
		if( !( typedCommand ) )
		{
			return false;
		}
		movementType = typedCommand.movementType;
		return true;
	}

	public constexpr function DoCleanUp() : Bool
	{
		return true;
	}

}

