class AIPatrolCommandPrologue extends AICommandHandlerBase
{
	editable inlined var outPatrolPath : AIArgumentMapping;

	protected override function UpdateCommand( context : ScriptExecutionContext, command : AICommand ) : AIbehaviorUpdateOutcome
	{
		var typedCommand : AIPatrolCommand;
		typedCommand = ( ( AIPatrolCommand )( command ) );
		if( !( typedCommand ) )
		{
			LogAIError( "'inCommand' doesn't have type 'AIPatrolCommand'." );
			return AIbehaviorUpdateOutcome.FAILURE;
		}
		if( !( typedCommand.pathParams ) )
		{
			LogAIError( "Patrol command has null 'pathParams'." );
			return AIbehaviorUpdateOutcome.FAILURE;
		}
		if( !( ScriptExecutionContext.SetMappingValue( context, outPatrolPath, typedCommand.pathParams ) ) )
		{
			return AIbehaviorUpdateOutcome.FAILURE;
		}
		return AIbehaviorUpdateOutcome.SUCCESS;
	}

}

