class AIScriptActionDelegate extends ScriptBehaviorDelegate
{
	private editable var actionPackageType : AIactionParamsPackageTypes;

	public static function GetActionPackageType( context : ScriptExecutionContext ) : AIactionParamsPackageTypes
	{
		var delegate : BehaviorDelegate;
		var actionDelegate : AIScriptActionDelegate;
		delegate = ScriptExecutionContext.GetClosestDelegate( context );
		while( delegate )
		{
			actionDelegate = ( ( AIScriptActionDelegate )( delegate ) );
			if( actionDelegate )
			{
				if( actionDelegate.actionPackageType != AIactionParamsPackageTypes.Undefined )
				{
					return actionDelegate.actionPackageType;
				}
			}
			delegate = delegate.GetParent();
		}
		return AIactionParamsPackageTypes.Default;
	}

}

