class AttackTypeHitPrereqCondition extends BaseHitPrereqCondition
{
	var m_attackType : gamedataAttackType;

	public override function SetData( recordID : TweakDBID )
	{
		var str : String;
		var result : gamedataAttackType;
		str = TweakDBInterface.GetString( recordID + T".attackType", "" );
		result = ( ( gamedataAttackType )( ( ( Int32 )( EnumValueFromString( "gamedataAttackType", str ) ) ) ) );
		if( ( ( Int32 )( result ) ) < 0 )
		{
			m_attackType = gamedataAttackType.Invalid;
		}
		else
		{
			m_attackType = ( ( gamedataAttackType )( result ) );
		}
		super.SetData( recordID );
	}

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var result : Bool;
		result = hitEvent.attackData.GetAttackType() == m_attackType;
		if( result )
		{
			result = CheckOnlyOncePerShot( hitEvent );
		}
		return ( ( m_invert ) ? ( !( result ) ) : ( result ) );
	}

}

