class AttackTagHitPrereqCondition extends BaseHitPrereqCondition
{
	var m_attackTag : CName;

	public override function SetData( recordID : TweakDBID )
	{
		m_attackTag = TweakDBInterface.GetCName( recordID + T".attackTag", '' );
		super.SetData( recordID );
	}

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var attackRecord : Attack_GameEffect_Record;
		var result : Bool;
		attackRecord = ( ( Attack_GameEffect_Record )( hitEvent.attackData.GetAttackDefinition().GetRecord() ) );
		result = attackRecord.AttackTag() == m_attackTag;
		return ( ( m_invert ) ? ( !( result ) ) : ( result ) );
	}

}

