class DismembermentTriggeredHitPrereqCondition extends BaseHitPrereqCondition
{
	private var m_currValue : Uint32;
	default m_currValue = 0;

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var bb : IBlackboard;
		var dismembermentInfo : DismembermentInstigatedInfo;
		bb = GameInstance.GetBlackboardSystem( hitEvent.attackData.GetInstigator().GetGame() ).Get( GetAllBlackboardDefs().PlayerPerkData );
		dismembermentInfo = ( ( DismembermentInstigatedInfo )( bb.GetVariant( GetAllBlackboardDefs().PlayerPerkData.DismembermentInstigated ) ) );
		if( m_currValue != dismembermentInfo.value )
		{
			m_currValue = dismembermentInfo.value;
			return true;
		}
		return false;
	}

}

