class HitFlagHitPrereqCondition extends BaseHitPrereqCondition
{
	var m_hitFlag : hitFlag;

	public override function SetData( recordID : TweakDBID )
	{
		var str : String;
		str = TweakDBInterface.GetString( recordID + T".hitFlag", "" );
		m_hitFlag = ( ( hitFlag )( ( ( Int32 )( EnumValueFromString( "hitFlag", str ) ) ) ) );
		super.SetData( recordID );
	}

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var result : Bool;
		result = hitEvent.attackData.HasFlag( m_hitFlag );
		if( result )
		{
			result = CheckOnlyOncePerShot( hitEvent );
		}
		return ( ( m_invert ) ? ( !( result ) ) : ( result ) );
	}

}

