class HitIsBodyPartTorsoPrereqState extends GenericHitPrereqState
{

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var result : Bool;
		var shape : HitShapeData;
		var empty : HitShapeData;
		shape = ( ( HitShapeData )( hitEvent.hitRepresentationResult.hitShapes[ 0 ] ) );
		if( shape != empty )
		{
			result = HitShapeUserDataBase.IsHitReactionZoneTorso( ( ( HitShapeUserDataBase )( shape.userData ) ) );
			return result;
		}
		return false;
	}

}

class HitIsBodyPartTorsoPrereq extends GenericHitPrereq
{
}

