class InstigatorTypeHitPrereqCondition extends BaseHitPrereqCondition
{
	var m_instigatorType : CName;

	public override function SetData( recordID : TweakDBID )
	{
		m_instigatorType = TweakDBInterface.GetCName( recordID + T".instigatorType", '' );
		super.SetData( recordID );
	}

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var result : Bool;
		switch( m_instigatorType )
		{
			case 'Player':
				result = ( ( PlayerPuppet )( hitEvent.attackData.GetInstigator() ) );
			break;
			case 'Puppet':
				result = ( ( ScriptedPuppet )( hitEvent.attackData.GetInstigator() ) );
			break;
			default:
				return false;
		}
		if( result )
		{
			result = CheckOnlyOncePerShot( hitEvent );
		}
		return ( ( m_invert ) ? ( !( result ) ) : ( result ) );
	}

}

