class TargetNPCTypeHitPrereqCondition extends BaseHitPrereqCondition
{
	var m_type : gamedataNPCType;

	public override function SetData( recordID : TweakDBID )
	{
		var str : String;
		str = TweakDBInterface.GetString( recordID + T".npcType", "" );
		m_type = ( ( gamedataNPCType )( ( ( Int32 )( EnumValueFromString( "gamedataNPCType", str ) ) ) ) );
		super.SetData( recordID );
	}

	public override function Evaluate( hitEvent : gameHitEvent ) : Bool
	{
		var result : Bool;
		var objectToCheck : weak< ScriptedPuppet >;
		objectToCheck = ( ( ScriptedPuppet )( hitEvent.target ) );
		if( objectToCheck )
		{
			result = objectToCheck.GetNPCType() == m_type;
			if( result )
			{
				result = CheckOnlyOncePerShot( hitEvent );
			}
			return ( ( m_invert ) ? ( !( result ) ) : ( result ) );
		}
		return false;
	}

}

