exec function SetZoneType( gameInstance : GameInstance, zoneType : String )
{
	var intValue : Int32;
	intValue = StringToInt( zoneType );
	SetFactValue( gameInstance, 'CityAreaType', intValue );
}

exec function SetQuestWeaponState( gameInstance : GameInstance, weaponState : String )
{
	SetFactValue( gameInstance, 'ForceSafeState', 0 );
	SetFactValue( gameInstance, 'ForceEmptyHands', 0 );
	switch( StringToInt( weaponState ) )
	{
		case 1:
			SetFactValue( gameInstance, 'ForceSafeState', 1 );
		break;
		case 2:
			SetFactValue( gameInstance, 'ForceEmptyHands', 1 );
		break;
		default:
			break;
	}
}

exec function RequestItem( gameInstance : GameInstance, itemTDBID : TweakDBID, slotID : TweakDBID )
{
	var playerObject : GameObject;
	var param : parameterRequestItem;
	var request : RequestItemParam;
	var psmEvent : PSMPostponedParameterScriptable;
	playerObject = GameInstance.GetPlayerSystem( gameInstance ).GetLocalPlayerMainGameObject();
	if( playerObject )
	{
		request.itemIDToEquip = ItemID.CreateQuery( itemTDBID );
		request.slotID = slotID;
		request.forceFirstEquip = true;
		param = new parameterRequestItem;
		param.requests.PushBack( request );
		psmEvent = new PSMPostponedParameterScriptable;
		psmEvent.value = param;
		psmEvent.id = 'requestItem';
		playerObject.QueueEvent( psmEvent );
	}
}

