importonly class FriendlyFireParams extends IScriptable
{
	public import final function SetShooter( attitude : weak< AttitudeAgent >, slotName : CName, attachmentName : CName );
	public import final function SetGeometry( spread : Float, maxRange : Float );
	public import final function SetCurrentTargetComponent( currentTarget : weak< TargetingComponent > );
	public import final function SetCurrentTargetObject( currentTarget : weak< GameObject > );
	public import final function SetFFApplyAttitude( FFApplyAttitude : EAIAttitude );
}

importonly abstract class IFriendlyFireSystem extends IGameSystem
{
	public import final function StartChecking( params : FriendlyFireParams ) : Uint32;
	public import final function StopChecking( id : Uint32 ) : Bool;
	public import final function Check( id : Uint32 ) : Bool;
	public import final function UpdateCurrentTargetComponent( id : Uint32, currentTarget : weak< TargetingComponent > );
	public import final function UpdateCurrentTargetObject( id : Uint32, currentTarget : weak< GameObject > );
	public import final function SetFFApplyAttitude( id : Uint32, FFApplyAttitude : Uint32 );
}

