class AlwaysTruePrereqState extends PrereqState
{
}

class AlwaysTruePrereq extends IScriptablePrereq
{

	protected export const override function OnApplied( state : PrereqState, game : GameInstance, context : IScriptable )
	{
		( ( AlwaysTruePrereqState )( state ) ).OnChanged( true );
	}

	public export const override function IsFulfilled( game : GameInstance, context : IScriptable ) : Bool
	{
		return true;
	}

}

