struct at_uiWidgetData
{
	var widgetATID : String;
	var layerType : inkELayerType;
	var parentGameController : CName;
}

import class at_uiUserData extends inkUserData
{
	import var atid : String;
}

import enum inkELayerType : Uint8
{
	Watermarks,
	WaitingSign,
	SystemNotifications,
	Loading,
	GameNotifications,
	Menu,
	Video,
	HUD,
	Editor,
	World,
	Offscreen,
	Advertisements,
	StreetSigns,
	PhotoMode,
	Debug,
	MAX,
}

operator[]( out widgetDataObject : at_uiWidgetData, widgetATID : String ) : Bool
{
	return widgetDataObject.widgetATID == widgetATID;
}

import function AT_AddATID( widget : weak< inkWidget >, const atid : ref< String > );
