class BodyDisposalPSMPrereqState extends PlayerStateMachinePrereqState
{
}

class BodyDisposalPSMPrereq extends PlayerStateMachinePrereq
{

	protected export const override function OnRegister( state : PrereqState, game : GameInstance, context : IScriptable ) : Bool
	{
		var bb : IBlackboard;
		var castedState : BodyDisposalPSMPrereqState;
		bb = GameInstance.GetBlackboardSystem( game ).GetLocalInstanced( ( ( ScriptedPuppet )( context ) ).GetEntityID(), GetAllBlackboardDefs().PlayerStateMachine );
		castedState = ( ( BodyDisposalPSMPrereqState )( state ) );
		castedState.m_owner = ( ( GameObject )( context ) );
		castedState.m_prevValue = bb.GetInt( GetAllBlackboardDefs().PlayerStateMachine.BodyDisposalDetailed );
		castedState.m_listenerInt = bb.RegisterListenerInt( GetAllBlackboardDefs().PlayerStateMachine.BodyDisposalDetailed, castedState, 'OnStateUpdate' );
		return false;
	}

	protected export const override function OnUnregister( state : PrereqState, game : GameInstance, context : IScriptable )
	{
		var bb : IBlackboard;
		var castedState : BodyDisposalPSMPrereqState;
		bb = GameInstance.GetBlackboardSystem( game ).GetLocalInstanced( ( ( ScriptedPuppet )( context ) ).GetEntityID(), GetAllBlackboardDefs().PlayerStateMachine );
		castedState = ( ( BodyDisposalPSMPrereqState )( state ) );
		bb.UnregisterListenerInt( GetAllBlackboardDefs().PlayerStateMachine.BodyDisposalDetailed, castedState.m_listenerInt );
	}

	protected const override function GetStateMachineEnum() : String
	{
		return "gamePSMDetailedBodyDisposal";
	}

	protected const override function GetCurrentPSMStateIndex( bb : IBlackboard ) : Int32
	{
		return bb.GetInt( GetAllBlackboardDefs().PlayerStateMachine.BodyDisposalDetailed );
	}

}

