class SimpleBinkGameController extends DeviceInkGameControllerBase
{
	protected var playCommonAd : Bool;
	default playCommonAd = true;
	[ category = "OBSOLETE - Widget Paths" ]
	protected editable var m_Video1Path : CName;
	default m_Video1Path = 'Video1';
	[ category = "OBSOLETE - Widget Paths" ]
	protected editable var m_Video2Path : CName;
	default m_Video2Path = 'Video2';
	[ category = "Widget Refs" ]
	private editable var m_Video1 : inkVideoRef;
	[ category = "Widget Refs" ]
	private editable var m_Video2 : inkVideoRef;

	protected event OnInitialize()
	{
		super.OnInitialize();
		if( playCommonAd )
		{
			StartVideo1();
		}
	}

	protected event OnUninitialize() {}

	public function switchAd()
	{
		if( playCommonAd )
		{
			StartVideo2();
			playCommonAd = false;
		}
		else
		{
			StartVideo1();
			playCommonAd = true;
		}
	}

	public function StartVideo2()
	{
		inkVideoRef.Stop( m_Video2 );
		inkVideoRef.SetVisible( m_Video1, false );
		inkVideoRef.SetVisible( m_Video2, true );
		inkVideoRef.Play( m_Video2 );
	}

	private function StartVideo1()
	{
		inkVideoRef.Stop( m_Video1 );
		inkVideoRef.SetVisible( m_Video2, false );
		inkVideoRef.SetVisible( m_Video1, true );
		inkVideoRef.Play( m_Video1 );
	}

}

