class LowFPSSelectCoverMode extends AIbehaviortaskScript
{

	protected export override function Activate( context : ScriptExecutionContext )
	{
		var osc : ObjectSelectionComponent;
		osc = GetPuppet( context ).GetObjectSelectionComponent();
		if( !( osc ) )
		{
			return;
		}
		osc.PauseCoversProcessing( true );
	}

	protected export override function Deactivate( context : ScriptExecutionContext )
	{
		var osc : ObjectSelectionComponent;
		osc = GetPuppet( context ).GetObjectSelectionComponent();
		if( !( osc ) )
		{
			return;
		}
		osc.PauseCoversProcessing( false );
	}

}

