class TeleportFailsafeHelper extends AIbehaviortaskScript
{

	protected override function Activate( context : ScriptExecutionContext )
	{
		var puppet : weak< ScriptedPuppet >;
		ScriptExecutionContext.DebugLog( context, 'Locomotion', "Failsafe teleportation" );
		puppet = ( ( ScriptedPuppet )( ScriptExecutionContext.GetOwner( context ) ) );
		ScriptExecutionContext.SetArgumentVector( context, 'TeleportDestination', puppet.GetMovePolicesComponent().GetDestination() );
	}

}

