import final class AnimVisibilityChangedEvent extends Event
{
	import var isVisible : Bool;
}

importonly final class AnimParamsEvent extends Event
{
	public import function GetParameterValue( paramName : CName, value : ref< Float > ) : Bool;
	public import function PushParameterValue( paramName : CName, value : Float );
}

import class AnimationSystem extends IScriptable
{
	public import function SetForcedVisible( entityId : EntityID, value : Bool );
	public import function SetForcedVisibleOnlyInFrustum( entityId : EntityID, value : Bool );
	public import function EnterCombatMode( entityId : EntityID );
	public import function ExitCombatMode( entityId : EntityID );
}

