importonly struct GOGRewardPack
{
	import const var id : String;
	import const var title : String;
	import const var reason : String;
	import const var iconSlot : CName;
	import const var rewards : array< Uint64 >;
}

importonly abstract class IOnlineSystem extends IGameSystem
{
	public import function GetStatus() : GOGRewardsSystemStatus;
	public import function GetError() : GOGRewardsSystemErrors;
	public import function RequestInitialStatus();
	public import function SignOut();
	public import function FindRewardRecordByRewardToken( token : Uint64 ) : weak< GOGReward_Record >;
	public import function IsRewardUnlocked( rewardRecord : GOGReward_Record ) : Bool;
	public import function GetUnlockedRewardPacks() : array< GOGRewardPack >;
	public import function GetRegistrationUrl() : String;
}

import enum GOGRewardsSystemStatus
{
	Uninitialized,
	GeneratingCPID,
	CheckingRegistrationStatus,
	RegistrationPending,
	Registered,
	Error,
}

import enum GOGRewardsSystemErrors
{
	None,
	RequestFailed,
	TemporaryFailure,
	NoInternetConnection,
	NotSignedInGalaxy,
	NotSignedInLauncher,
	NotSignedInGame,
}

import function GOGRewardSystemErrorToDisplayString( error : GOGRewardsSystemErrors ) : String;
