importonly abstract class IPreventionSpawnSystem extends IGameSystem
{
}

import class PreventionSpawnSystem extends IPreventionSpawnSystem
{
	public import function RequestSpawn( recordID : TweakDBID, preventionLevel : Uint32, spawnTransform : WorldTransform ) : EntityID;
	public import function RequestVehicleSpawn( recordID : TweakDBID, districtRecordID : TweakDBID, preventionLevel : Uint32 );
	public import function ReinitVehicle( vehicle : weak< VehicleObject > );
	public import function RequestDespawn( entityID : EntityID );
	public import function RequestDespawnPreventionLevel( preventionLevel : Uint32 );
	public import function GetNumberOfSpawnedPreventionUnits() : Int32;
	public import function IsPreventionVehiclePrototypeEnabled() : Bool;
	public import const function FindPursuitPointsRange( playerPos : Vector4, pos : Vector4, dir : Vector4, radiusMin : Float, radiusMax : Float, count : Int32, navVisCheck : Bool, agentSize : NavGenAgentSize, out results : array< Vector4 >, out fallbackResults : array< Vector4 > ) : Bool;
	public import function RegisterEntityDeathCallback( scriptable : weak< IScriptable >, functionName : String, entityID : EntityID );
	public import function UnregisterEntityDeathCallback( scriptable : weak< IScriptable >, functionName : String, entityID : EntityID );
	public import function JoinTraffic( veh : weak< VehicleObject > );

	protected function SpawnCallback( spawnedObject : GameObject )
	{
		if( spawnedObject.IsPuppet() )
		{
			PreventionSystem.RegisterPoliceUnit( spawnedObject.GetGame(), ( ( ScriptedPuppet )( spawnedObject ) ) );
		}
		else if( spawnedObject.IsVehicle() )
		{
			PreventionSystem.RegisterPoliceVehicle( spawnedObject.GetGame(), ( ( VehicleObject )( spawnedObject ) ) );
		}
	}

}

