import enum worldRainIntensity
{
	NoRain,
	LightRain,
	HeavyRain,
}

import class RainEvent extends Event
{
	import var rainIntensity : worldRainIntensity;
}

import class WeatherScriptListener extends IScriptable
{
	public virtual function OnRainIntensityChanged( rainIntensity : Float );
	public virtual function OnRainIntensityTypeChanged( rainIntensityType : worldRainIntensity );
}

importonly class WeatherSystem extends IScriptable
{
	public import function RegisterWeatherListener( callback : WeatherScriptListener ) : Uint32;
	public import function UnregisterWeatherListener( callbackId : Uint32 );
	public import const function GetRainMoisture() : Float;
	public import const function GetRainPuddles() : Float;
	public import const function GetRainIntensity() : Float;
	public import const function GetRainIntensityType() : worldRainIntensity;
}

