class RewireEvent extends Event
{
	var ownerID : EntityID;
	var activatorID : EntityID;
	var executor : weak< GameObject >;
	var state : EDrillMachineRewireState;
	var sucess : Bool;
}

class DrillScanPostProcessEvent extends Event
{
	var IsEnabled : Bool;
}

class DrillScanEvent extends Event
{
	var IsScanning : Bool;
}

class DrillerUIEvent extends Event
{
	var actionChosen : InteractionChoice;
	var activator : weak< GameObject >;
}

enum EDrillMachineRewireState
{
	InsideInteractionRange = 0,
	OutsideInteractionRange = 1,
	InteractionStarted = 2,
	InteractionFinished = 3,
	RewireStarted = 4,
	RewireFinished = 5,
}

